create table Car (
	id INT,
	CarMake VARCHAR(50),
	CarModel VARCHAR(50),
	CarYear VARCHAR(50)
);
insert into Car (id, CarMake, CarModel, CarYear) values (1, 'Mercedes-Benz', 'SLR McLaren', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (2, 'Ford', 'Aerostar', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (3, 'Chevrolet', 'Corvette', 1960);
insert into Car (id, CarMake, CarModel, CarYear) values (4, 'Jeep', 'Cherokee', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (5, 'Porsche', 'Carrera GT', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (6, 'Buick', 'Regal', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (7, 'Aston Martin', 'DB9', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (8, 'Mazda', 'MX-5', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (9, 'GMC', 'Vandura 2500', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (10, 'Chevrolet', '3500', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (11, 'Infiniti', 'EX', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (12, 'Pontiac', 'Bonneville', 1968);
insert into Car (id, CarMake, CarModel, CarYear) values (13, 'Volkswagen', 'Golf', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (14, 'GMC', 'Sierra 1500', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (15, 'Cadillac', 'Escalade EXT', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (16, 'BMW', '530', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (17, 'Saab', '9000', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (18, 'Buick', 'Park Avenue', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (19, 'Toyota', 'Tundra', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (20, 'Dodge', 'Ram Wagon B250', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (21, 'Jeep', 'Commander', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (22, 'Buick', 'Skyhawk', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (23, 'BMW', 'Z8', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (24, 'Mercury', 'Lynx', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (25, 'Toyota', 'TundraMax', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (26, 'BMW', '3 Series', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (27, 'Honda', 'Accord', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (28, 'Dodge', 'Dakota Club', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (29, 'GMC', 'Sonoma Club Coupe', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (30, 'Plymouth', 'Fury', 1964);
insert into Car (id, CarMake, CarModel, CarYear) values (31, 'Porsche', '911', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (32, 'Pontiac', 'Trans Sport', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (33, 'Hyundai', 'Sonata', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (34, 'Chevrolet', 'Blazer', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (35, 'Saab', '9-3', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (36, 'Lotus', 'Elise', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (37, 'Porsche', 'Cayman', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (38, 'GMC', 'Safari', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (39, 'Chevrolet', 'Silverado 2500', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (40, 'GMC', 'Savana 2500', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (41, 'Chevrolet', 'Camaro', 1970);
insert into Car (id, CarMake, CarModel, CarYear) values (42, 'Isuzu', 'Ascender', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (43, 'Chrysler', 'Concorde', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (44, 'Mercedes-Benz', 'SL-Class', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (45, 'Saab', '9-5', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (46, 'Mercury', 'Marauder', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (47, 'Bentley', 'Azure', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (48, 'Honda', 'Civic', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (49, 'Acura', 'TL', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (50, 'Porsche', 'Cayenne', 2013);
insert into Car (id, CarMake, CarModel, CarYear) values (51, 'Ford', 'F150', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (52, 'Chevrolet', 'Camaro', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (53, 'Jaguar', 'X-Type', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (54, 'Mazda', 'MX-5', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (55, 'Mazda', 'RX-8', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (56, 'Saab', '900', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (57, 'Pontiac', 'Bonneville', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (58, 'Suzuki', 'Swift', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (59, 'Ford', 'Econoline E250', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (60, 'Ford', 'Aspire', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (61, 'Pontiac', 'G5', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (62, 'Kia', 'Sorento', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (63, 'Mazda', 'Familia', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (64, 'Chevrolet', 'Camaro', 1981);
insert into Car (id, CarMake, CarModel, CarYear) values (65, 'Kia', 'Sedona', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (66, 'Chevrolet', 'Suburban 2500', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (67, 'Ferrari', '458 Italia', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (68, 'Suzuki', 'XL-7', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (69, 'Saturn', 'VUE', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (70, 'Subaru', 'Outback', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (71, 'Dodge', 'Ram 2500', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (72, 'Audi', 'V8', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (73, 'Hummer', 'H1', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (74, 'Jeep', 'Commander', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (75, 'Infiniti', 'QX56', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (76, 'Chevrolet', 'Impala', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (77, 'Pontiac', 'Solstice', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (78, 'BMW', 'Z3', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (79, 'Mercedes-Benz', 'G-Class', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (80, 'Ford', 'Mustang', 1983);
insert into Car (id, CarMake, CarModel, CarYear) values (81, 'Suzuki', 'SJ', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (82, 'Land Rover', 'Range Rover', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (83, 'Toyota', 'Land Cruiser', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (84, 'Buick', 'LeSabre', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (85, 'Audi', 'RS6', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (86, 'Dodge', 'Dakota', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (87, 'Mercury', 'Mountaineer', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (88, 'Volkswagen', 'Cabriolet', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (89, 'Chevrolet', 'Express 3500', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (90, 'Pontiac', 'Grand Prix', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (91, 'Dodge', 'Ram Van 3500', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (92, 'Lexus', 'IS', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (93, 'Scion', 'xB', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (94, 'Mazda', 'Mazda3', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (95, 'Mercedes-Benz', 'SLK-Class', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (96, 'Lexus', 'RX', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (97, 'Infiniti', 'G35', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (98, 'Jaguar', 'X-Type', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (99, 'Honda', 'Accord Crosstour', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (100, 'Dodge', 'Caliber', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (101, 'Volkswagen', 'New Beetle', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (102, 'Volvo', 'XC60', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (103, 'Hyundai', 'Genesis', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (104, 'Pontiac', '1000', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (105, 'Audi', 'TT', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (106, 'Lotus', 'Elan', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (107, 'GMC', 'Suburban 2500', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (108, 'Audi', 'RS4', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (109, 'Mercedes-Benz', 'SLK-Class', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (110, 'Buick', 'Century', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (111, 'Cadillac', 'Seville', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (112, 'GMC', 'Savana 2500', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (113, 'Mercedes-Benz', 'CLS-Class', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (114, 'Subaru', 'Forester', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (115, 'Honda', 'Pilot', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (116, 'Suzuki', 'Daewoo Lacetti', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (117, 'Mitsubishi', 'Eclipse', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (118, 'Plymouth', 'Breeze', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (119, 'Porsche', '968', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (120, 'GMC', 'Yukon XL 1500', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (121, 'Lamborghini', 'Murciélago', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (122, 'Lincoln', 'Town Car', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (123, 'Ford', 'Escort ZX2', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (124, 'Ford', 'Explorer Sport Trac', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (125, 'Volvo', 'XC90', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (126, 'Lexus', 'IS', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (127, 'Maybach', '62', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (128, 'GMC', 'Suburban 2500', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (129, 'Pontiac', 'Grand Am', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (130, 'Chevrolet', 'Express', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (131, 'Lincoln', 'Navigator L', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (132, 'Infiniti', 'FX', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (133, 'Isuzu', 'Trooper', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (134, 'GMC', 'Rally Wagon 2500', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (135, 'Volkswagen', 'Eos', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (136, 'Ford', 'F-Series', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (137, 'Ford', 'Taurus', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (138, 'Saturn', 'VUE', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (139, 'Toyota', 'MR2', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (140, 'Mercedes-Benz', 'E-Class', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (141, 'Chevrolet', 'Camaro', 1968);
insert into Car (id, CarMake, CarModel, CarYear) values (142, 'Dodge', 'Caravan', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (143, 'Suzuki', 'Grand Vitara', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (144, 'Nissan', 'Titan', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (145, 'Nissan', 'Altima', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (146, 'BMW', 'M6', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (147, 'Buick', 'Skyhawk', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (148, 'GMC', 'Envoy', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (149, 'Cadillac', 'DeVille', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (150, 'Ford', 'E-Series', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (151, 'Mercury', 'Cougar', 1967);
insert into Car (id, CarMake, CarModel, CarYear) values (152, 'Toyota', 'Sequoia', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (153, 'Hummer', 'H3', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (154, 'Isuzu', 'Rodeo', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (155, 'Ford', 'Ranger', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (156, 'Ford', 'Mustang', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (157, 'Lincoln', 'Town Car', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (158, 'Acura', 'Integra', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (159, 'Chevrolet', 'Malibu', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (160, 'Hyundai', 'Azera', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (161, 'Mitsubishi', 'Chariot', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (162, 'Pontiac', 'Firebird', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (163, 'Ford', 'Ranger', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (164, 'Mazda', 'RX-7', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (165, 'Land Rover', 'Range Rover Evoque', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (166, 'Buick', 'Electra', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (167, 'Volvo', 'XC70', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (168, 'GMC', 'Suburban 1500', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (169, 'Chevrolet', 'Express 1500', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (170, 'Jaguar', 'XJ Series', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (171, 'Lamborghini', 'Murciélago LP640', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (172, 'Chevrolet', 'Suburban 2500', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (173, 'Dodge', 'Nitro', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (174, 'Mitsubishi', 'Raider', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (175, 'Toyota', 'Tacoma Xtra', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (176, 'Chevrolet', 'G-Series 2500', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (177, 'Nissan', '300ZX', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (178, 'Saab', '900', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (179, 'Ford', 'E-Series', 1963);
insert into Car (id, CarMake, CarModel, CarYear) values (180, 'Mercedes-Benz', '400E', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (181, 'Subaru', 'Alcyone SVX', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (182, 'Audi', 'Coupe GT', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (183, 'Chevrolet', '2500', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (184, 'Scion', 'xD', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (185, 'Acura', 'TL', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (186, 'Nissan', 'Quest', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (187, 'GMC', 'Sonoma', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (188, 'GMC', 'Sierra 1500', 2013);
insert into Car (id, CarMake, CarModel, CarYear) values (189, 'Ford', 'F450', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (190, 'Ford', 'F-Series', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (191, 'Lexus', 'GS', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (192, 'Ford', 'LTD Crown Victoria', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (193, 'Porsche', 'Cayenne', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (194, 'Chevrolet', 'Metro', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (195, 'Ford', 'GT500', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (196, 'Pontiac', 'G6', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (197, 'Lexus', 'LS', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (198, 'Ford', 'F-Series', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (199, 'Mazda', 'Familia', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (200, 'Lincoln', 'Navigator L', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (201, 'Alfa Romeo', '164', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (202, 'Geo', 'Prizm', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (203, 'Ford', 'F150', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (204, 'Toyota', 'Celica', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (205, 'Pontiac', 'Grand Prix', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (206, 'Volkswagen', 'GTI', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (207, 'Renault', 'Alliance', 1983);
insert into Car (id, CarMake, CarModel, CarYear) values (208, 'Dodge', 'Daytona', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (209, 'Volkswagen', 'Jetta', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (210, 'BMW', '545', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (211, 'Chrysler', 'Town & Country', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (212, 'Pontiac', 'Sunbird', 1983);
insert into Car (id, CarMake, CarModel, CarYear) values (213, 'Audi', 'R8', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (214, 'Dodge', 'Grand Caravan', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (215, 'Mitsubishi', '3000GT', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (216, 'Chevrolet', 'Express 3500', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (217, 'Lexus', 'GX', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (218, 'Chrysler', 'Town & Country', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (219, 'Chrysler', 'PT Cruiser', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (220, 'Chevrolet', '3500', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (221, 'Kia', 'Soul', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (222, 'Nissan', 'Maxima', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (223, 'Dodge', 'Journey', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (224, 'Mercury', 'Marauder', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (225, 'Chevrolet', 'Silverado', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (226, 'Ford', 'E-Series', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (227, 'Chrysler', 'Town & Country', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (228, 'Acura', 'Integra', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (229, 'Mitsubishi', 'Outlander', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (230, 'Suzuki', 'XL-7', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (231, 'BMW', '6 Series', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (232, 'Suzuki', 'Daewoo Lacetti', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (233, 'Mercury', 'Cougar', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (234, 'BMW', '7 Series', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (235, 'Jeep', 'Commander', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (236, 'Chevrolet', '2500', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (237, 'Audi', 'A6', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (238, 'Land Rover', 'Range Rover', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (239, 'Suzuki', 'Reno', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (240, 'Toyota', 'MR2', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (241, 'Mercury', 'Grand Marquis', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (242, 'Honda', 'Ridgeline', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (243, 'Kia', 'Sephia', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (244, 'Maybach', '57', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (245, 'Chevrolet', 'Lumina', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (246, 'Toyota', 'MR2', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (247, 'Jaguar', 'XK Series', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (248, 'BMW', 'Z4', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (249, 'Oldsmobile', 'Silhouette', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (250, 'Mazda', 'RX-8', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (251, 'Mazda', 'MX-5', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (252, 'Chevrolet', 'Blazer', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (253, 'Chevrolet', 'Camaro', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (254, 'Ford', 'E-Series', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (255, 'Land Rover', 'Defender', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (256, 'Dodge', 'Caravan', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (257, 'Pontiac', 'Grand Am', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (258, 'Dodge', 'Spirit', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (259, 'Mazda', 'Navajo', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (260, 'Lexus', 'LS', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (261, 'Nissan', 'Maxima', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (262, 'Subaru', 'Impreza', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (263, 'Saab', '900', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (264, 'Mercedes-Benz', '300CE', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (265, 'Ford', 'E250', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (266, 'Hyundai', 'Accent', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (267, 'Hyundai', 'Azera', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (268, 'BMW', 'X5', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (269, 'Mercury', 'Cougar', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (270, 'Land Rover', 'Sterling', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (271, 'Honda', 'del Sol', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (272, 'Eagle', 'Talon', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (273, 'Pontiac', 'Firefly', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (274, 'Cadillac', 'DeVille', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (275, 'Ford', 'Taurus', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (276, 'Volkswagen', 'GTI', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (277, 'Maserati', 'Coupe', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (278, 'Hyundai', 'Azera', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (279, 'Ford', 'Tempo', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (280, 'GMC', 'Sierra 2500', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (281, 'GMC', 'Sierra 1500', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (282, 'Mazda', 'CX-7', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (283, 'Subaru', 'Impreza', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (284, 'Volkswagen', 'Golf', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (285, 'Daewoo', 'Leganza', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (286, 'Mazda', 'MPV', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (287, 'Land Rover', 'Range Rover', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (288, 'Maserati', 'Coupe', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (289, 'Kia', 'Optima', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (290, 'Pontiac', 'Torrent', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (291, 'Maserati', 'Gran Sport', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (292, 'Aston Martin', 'DBS', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (293, 'Kia', 'Amanti', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (294, 'Porsche', '911', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (295, 'Suzuki', 'Cultus', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (296, 'Porsche', '911', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (297, 'Mazda', '626', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (298, 'Suzuki', 'Daewoo Magnus', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (299, 'Chevrolet', 'Traverse', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (300, 'Dodge', 'Ram Van 2500', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (301, 'Dodge', 'Intrepid', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (302, 'Mitsubishi', 'Pajero', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (303, 'GMC', 'Sierra 2500', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (304, 'GMC', 'Safari', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (305, 'Mercedes-Benz', 'CL-Class', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (306, 'BMW', 'M3', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (307, 'Toyota', 'Tacoma Xtra', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (308, 'Maserati', 'Quattroporte', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (309, 'Lotus', 'Esprit', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (310, 'Toyota', 'Corolla', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (311, 'Volvo', 'S80', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (312, 'Audi', 'A8', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (313, 'Ford', 'Probe', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (314, 'BMW', '3 Series', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (315, 'GMC', 'Savana', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (316, 'Oldsmobile', 'Achieva', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (317, 'Lamborghini', 'Aventador', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (318, 'GMC', 'Sierra 3500', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (319, 'Volkswagen', 'Fox', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (320, 'Hummer', 'H1', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (321, 'Mercedes-Benz', 'Sprinter', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (322, 'Lexus', 'IS', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (323, 'Lincoln', 'Navigator', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (324, 'Chevrolet', 'Suburban 1500', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (325, 'Mercedes-Benz', 'E-Class', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (326, 'Saab', '9-5', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (327, 'Toyota', 'Matrix', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (328, 'Ford', 'E-Series', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (329, 'Lincoln', 'Town Car', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (330, 'Dodge', 'Grand Caravan', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (331, 'Pontiac', 'G6', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (332, 'Honda', 'Ridgeline', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (333, 'BMW', '8 Series', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (334, 'Hyundai', 'Genesis Coupe', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (335, 'Mercedes-Benz', '300SE', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (336, 'Ford', 'Edge', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (337, 'Ford', 'Focus', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (338, 'Land Rover', 'Discovery', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (339, 'Audi', 'A6', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (340, 'Chevrolet', 'Express 2500', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (341, 'Ford', 'Econoline E150', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (342, 'Nissan', 'Frontier', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (343, 'Mitsubishi', 'L300', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (344, 'Saturn', 'VUE', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (345, 'Pontiac', 'Sunbird', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (346, 'Honda', 'Prelude', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (347, 'Pontiac', 'GTO', 1973);
insert into Car (id, CarMake, CarModel, CarYear) values (348, 'Honda', 'Pilot', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (349, 'Acura', 'RDX', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (350, 'Mercedes-Benz', 'SL-Class', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (351, 'BMW', 'X3', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (352, 'Plymouth', 'Colt Vista', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (353, 'Mitsubishi', 'Tredia', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (354, 'Ram', '3500', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (355, 'Nissan', 'Sentra', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (356, 'Mercedes-Benz', 'C-Class', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (357, 'Isuzu', 'Rodeo', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (358, 'Dodge', 'Grand Caravan', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (359, 'Nissan', 'Armada', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (360, 'Mitsubishi', 'Lancer Evolution', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (361, 'Dodge', 'Ram 3500', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (362, 'Oldsmobile', 'Cutlass Supreme', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (363, 'Dodge', 'Dakota', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (364, 'BMW', 'M6', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (365, 'GMC', 'Savana 2500', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (366, 'Plymouth', 'Neon', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (367, 'Subaru', 'XT', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (368, 'Lexus', 'LS', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (369, 'Mitsubishi', 'Diamante', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (370, 'Mitsubishi', 'Lancer', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (371, 'BMW', 'Z4', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (372, 'Audi', 'Coupe GT', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (373, 'Nissan', 'Versa', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (374, 'Suzuki', 'SJ', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (375, 'Mitsubishi', 'L300', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (376, 'Toyota', 'Camry', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (377, 'Lincoln', 'Mark LT', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (378, 'GMC', 'Yukon', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (379, 'Ferrari', 'F430', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (380, 'Volkswagen', 'Touareg', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (381, 'Lexus', 'LS', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (382, 'BMW', '7 Series', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (383, 'Ford', 'Explorer Sport', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (384, 'Dodge', 'Ram Van B150', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (385, 'Kia', 'Rio', 2013);
insert into Car (id, CarMake, CarModel, CarYear) values (386, 'Saab', '9-3', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (387, 'Toyota', 'FJ Cruiser', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (388, 'Jeep', 'Compass', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (389, 'Chevrolet', '2500', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (390, 'Buick', 'Reatta', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (391, 'Ford', 'Flex', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (392, 'Chevrolet', 'Camaro', 1978);
insert into Car (id, CarMake, CarModel, CarYear) values (393, 'Dodge', 'Ram Van 3500', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (394, 'Volkswagen', 'GLI', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (395, 'Mazda', 'B-Series', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (396, 'Lamborghini', 'Diablo', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (397, 'Porsche', '911', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (398, 'Suzuki', 'Sidekick', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (399, 'Mercedes-Benz', 'C-Class', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (400, 'Volkswagen', 'GTI', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (401, 'Ford', 'Windstar', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (402, 'Ford', 'Expedition', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (403, 'Acura', 'TL', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (404, 'Honda', 'Fit', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (405, 'Volkswagen', 'rio', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (406, 'GMC', '3500 Club Coupe', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (407, 'Audi', 'Allroad', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (408, 'Rolls-Royce', 'Phantom', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (409, 'Acura', 'RDX', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (410, 'Hyundai', 'Santa Fe', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (411, 'Ford', 'Ranger', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (412, 'Chrysler', 'New Yorker', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (413, 'Ford', 'Mustang', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (414, 'Nissan', 'Sentra', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (415, 'Chevrolet', 'Suburban 1500', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (416, 'Mazda', 'MPV', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (417, 'Daewoo', 'Lanos', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (418, 'Honda', 'Prelude', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (419, 'Volkswagen', 'GTI', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (420, 'Porsche', '911', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (421, 'Kia', 'Optima', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (422, 'Maybach', '57', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (423, 'GMC', 'Suburban 2500', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (424, 'Volkswagen', 'rio', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (425, 'Porsche', 'Boxster', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (426, 'Dodge', 'Ram 1500 Club', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (427, 'Scion', 'xB', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (428, 'Daewoo', 'Leganza', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (429, 'Chevrolet', 'Silverado 2500', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (430, 'Jaguar', 'XK Series', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (431, 'Audi', 'RS4', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (432, 'Chevrolet', '3500', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (433, 'Acura', 'Integra', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (434, 'Buick', 'Lucerne', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (435, 'Toyota', 'Venza', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (436, 'Volvo', 'S60', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (437, 'Oldsmobile', 'Intrigue', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (438, 'Mercedes-Benz', 'W123', 1977);
insert into Car (id, CarMake, CarModel, CarYear) values (439, 'Chrysler', 'Concorde', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (440, 'Honda', 'Pilot', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (441, 'Ford', 'Escort', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (442, 'Nissan', 'NV1500', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (443, 'Kia', 'Sorento', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (444, 'Pontiac', 'Gemini', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (445, 'Ford', 'Expedition', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (446, 'Buick', 'Rendezvous', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (447, 'Geo', 'Storm', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (448, 'Mitsubishi', 'Eclipse', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (449, 'Aston Martin', 'Vantage', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (450, 'Chevrolet', 'Suburban 1500', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (451, 'GMC', 'Yukon XL 1500', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (452, 'Volkswagen', 'Touareg', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (453, 'Chevrolet', 'Tracker', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (454, 'Volkswagen', 'Quantum', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (455, 'Mitsubishi', 'Challenger', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (456, 'Buick', 'LaCrosse', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (457, 'Volvo', 'XC70', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (458, 'BMW', 'Z4 M', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (459, 'Lexus', 'ES', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (460, 'Volvo', 'S80', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (461, 'Audi', '90', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (462, 'Subaru', 'Impreza', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (463, 'Ford', 'Lightning', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (464, 'Hyundai', 'HED-5', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (465, 'Ford', 'Focus', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (466, 'Mazda', 'Mazda5', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (467, 'Chevrolet', 'Corvette', 1959);
insert into Car (id, CarMake, CarModel, CarYear) values (468, 'BMW', 'M5', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (469, 'Toyota', 'Venza', 2013);
insert into Car (id, CarMake, CarModel, CarYear) values (470, 'BMW', '7 Series', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (471, 'Volkswagen', 'rio', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (472, 'Volkswagen', 'GTI', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (473, 'Nissan', 'Altima', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (474, 'Tesla', 'Roadster', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (475, 'Saturn', 'Aura', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (476, 'Pontiac', 'Grand Prix', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (477, 'Audi', 'Cabriolet', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (478, 'Chevrolet', 'Suburban 2500', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (479, 'Lincoln', 'Town Car', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (480, 'Chevrolet', 'Caprice', 1983);
insert into Car (id, CarMake, CarModel, CarYear) values (481, 'Subaru', 'Legacy', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (482, 'Ford', 'Bronco', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (483, 'Saturn', 'VUE', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (484, 'GMC', '1500 Club Coupe', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (485, 'Acura', 'RL', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (486, 'Isuzu', 'Impulse', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (487, 'Lexus', 'LS', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (488, 'Isuzu', 'Rodeo Sport', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (489, 'Kia', 'Sephia', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (490, 'Honda', 'Odyssey', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (491, 'Toyota', 'Solara', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (492, 'Toyota', 'MR2', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (493, 'Mazda', 'RX-7', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (494, 'Mazda', '626', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (495, 'Ford', 'Fairlane', 1967);
insert into Car (id, CarMake, CarModel, CarYear) values (496, 'Ford', 'Club Wagon', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (497, 'Pontiac', 'Sunbird', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (498, 'BMW', '1 Series', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (499, 'Audi', 'TT', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (500, 'Chevrolet', 'Malibu', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (501, 'Suzuki', 'SJ', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (502, 'Nissan', 'Versa', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (503, 'Nissan', 'Frontier', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (504, 'GMC', 'Yukon XL 2500', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (505, 'Cadillac', 'XLR', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (506, 'Chevrolet', 'Malibu', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (507, 'Audi', '5000CS', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (508, 'Chevrolet', 'Corvette', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (509, 'Suzuki', 'XL7', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (510, 'Chevrolet', 'Suburban 1500', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (511, 'Ford', 'E250', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (512, 'Mercedes-Benz', 'W201', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (513, 'Subaru', 'Forester', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (514, 'Volkswagen', 'Fox', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (515, 'Mercury', 'Capri', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (516, 'Kia', 'Sorento', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (517, 'Mitsubishi', 'Galant', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (518, 'Subaru', 'Loyale', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (519, 'Acura', 'NSX', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (520, 'Mazda', 'MPV', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (521, 'Kia', 'Rondo', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (522, 'Mercedes-Benz', 'CLK-Class', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (523, 'BMW', '5 Series', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (524, 'Buick', 'LeSabre', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (525, 'Dodge', 'Grand Caravan', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (526, 'Plymouth', 'Neon', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (527, 'Hyundai', 'Accent', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (528, 'Land Rover', 'LR2', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (529, 'Mazda', 'RX-7', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (530, 'Plymouth', 'Fury', 1964);
insert into Car (id, CarMake, CarModel, CarYear) values (531, 'Land Rover', 'Freelander', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (532, 'Pontiac', 'LeMans', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (533, 'Saturn', 'S-Series', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (534, 'Ford', 'Bronco II', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (535, 'Porsche', 'Boxster', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (536, 'Plymouth', 'Breeze', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (537, 'Toyota', 'Tacoma Xtra', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (538, 'Chrysler', 'Town & Country', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (539, 'Toyota', 'Tacoma', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (540, 'MINI', 'Cooper Countryman', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (541, 'Lexus', 'GS', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (542, 'Mazda', '626', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (543, 'Porsche', '928', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (544, 'Chevrolet', 'Traverse', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (545, 'Chevrolet', 'G-Series G30', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (546, 'Ford', 'F150', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (547, 'Dodge', 'Avenger', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (548, 'Pontiac', 'Firebird', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (549, 'Chevrolet', 'Avalanche 2500', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (550, 'Dodge', 'Daytona', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (551, 'Pontiac', 'Bonneville', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (552, 'Maserati', 'Spyder', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (553, 'Chevrolet', 'Corvette', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (554, 'Ford', 'Expedition', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (555, 'Lamborghini', 'Diablo', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (556, 'GMC', 'Sierra', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (557, 'Suzuki', 'Aerio', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (558, 'Land Rover', 'LR2', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (559, 'Chevrolet', 'Express 1500', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (560, 'GMC', 'Yukon XL 2500', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (561, 'Dodge', 'Dakota Club', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (562, 'Ford', 'F-Series', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (563, 'Ford', 'Ranger', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (564, 'Ford', 'Econoline E350', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (565, 'Lamborghini', 'Gallardo', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (566, 'Ford', 'Crown Victoria', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (567, 'Ford', 'F-Series', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (568, 'Chevrolet', 'SSR', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (569, 'Mazda', 'Protege5', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (570, 'Buick', 'Riviera', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (571, 'Chrysler', 'Sebring', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (572, 'Mercedes-Benz', 'CLK-Class', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (573, 'GMC', 'Suburban 1500', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (574, 'Audi', 'Quattro', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (575, 'Chevrolet', 'Venture', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (576, 'Toyota', 'Land Cruiser', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (577, 'Suzuki', 'SX4', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (578, 'Mitsubishi', 'Montero', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (579, 'Mazda', 'MX-5', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (580, 'Ford', 'E350', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (581, 'Chevrolet', 'Classic', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (582, 'Nissan', 'Pathfinder', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (583, 'Mercedes-Benz', 'SLR McLaren', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (584, 'Volkswagen', 'rio', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (585, 'Infiniti', 'G', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (586, 'Mazda', 'RX-7', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (587, 'Lincoln', 'MKX', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (588, 'Jaguar', 'S-Type', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (589, 'Mitsubishi', 'Tundra', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (590, 'Dodge', 'Durango', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (591, 'Hummer', 'H1', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (592, 'Mercury', 'Villager', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (593, 'Pontiac', 'Vibe', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (594, 'Scion', 'FR-S', 2013);
insert into Car (id, CarMake, CarModel, CarYear) values (595, 'Toyota', 'FJ Cruiser', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (596, 'Chevrolet', 'Equinox', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (597, 'Toyota', 'Yaris', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (598, 'Eagle', 'Talon', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (599, 'Mercedes-Benz', 'W201', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (600, 'GMC', 'Yukon', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (601, 'Ford', 'Ranger', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (602, 'Chevrolet', 'Avalanche', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (603, 'Lamborghini', 'Murciélago', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (604, 'Lincoln', 'Mark VIII', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (605, 'Maserati', 'Quattroporte', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (606, 'Mazda', 'Protege5', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (607, 'Mitsubishi', '3000GT', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (608, 'Eagle', 'Talon', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (609, 'Acura', 'Legend', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (610, 'Infiniti', 'Q', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (611, 'Cadillac', 'Catera', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (612, 'Cadillac', 'CTS', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (613, 'GMC', 'Savana 2500', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (614, 'Lotus', 'Esprit', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (615, 'Pontiac', 'Grand Am', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (616, 'Toyota', 'Camry Hybrid', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (617, 'Toyota', 'Tacoma', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (618, 'Jaguar', 'XJ', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (619, 'Aston Martin', 'DBS', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (620, 'Mercedes-Benz', 'SL-Class', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (621, 'Pontiac', 'G3', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (622, 'Plymouth', 'Voyager', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (623, 'MINI', 'Cooper', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (624, 'Subaru', 'BRZ', 2013);
insert into Car (id, CarMake, CarModel, CarYear) values (625, 'Eagle', 'Vision', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (626, 'Volkswagen', 'Eurovan', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (627, 'Infiniti', 'EX', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (628, 'Jaguar', 'X-Type', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (629, 'Pontiac', 'Firefly', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (630, 'Suzuki', 'SX4', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (631, 'BMW', 'M3', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (632, 'Ford', 'F250', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (633, 'Ford', 'F250', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (634, 'Volkswagen', 'Golf', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (635, 'Chevrolet', 'Silverado', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (636, 'Lotus', 'Elan', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (637, 'Pontiac', 'Torrent', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (638, 'Chevrolet', 'Impala', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (639, 'Toyota', 'Previa', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (640, 'Audi', 'Cabriolet', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (641, 'Chevrolet', 'Camaro', 1979);
insert into Car (id, CarMake, CarModel, CarYear) values (642, 'Buick', 'Park Avenue', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (643, 'BMW', '3 Series', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (644, 'Chevrolet', 'Corvair 500', 1963);
insert into Car (id, CarMake, CarModel, CarYear) values (645, 'Plymouth', 'Grand Voyager', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (646, 'Porsche', '911', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (647, 'Mercedes-Benz', 'CLS-Class', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (648, 'Lotus', 'Esprit', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (649, 'Subaru', 'Forester', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (650, 'Land Rover', 'Discovery', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (651, 'Chrysler', 'Aspen', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (652, 'Dodge', 'Neon', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (653, 'Audi', '4000s Quattro', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (654, 'Ford', 'Ranger', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (655, 'Ferrari', 'F430', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (656, 'Isuzu', 'Rodeo', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (657, 'Hyundai', 'Accent', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (658, 'BMW', 'M3', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (659, 'Aston Martin', 'DBS', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (660, 'Chevrolet', 'Express 2500', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (661, 'Ford', 'Fusion', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (662, 'Hyundai', 'Tiburon', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (663, 'Ford', 'F150', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (664, 'Cadillac', 'SRX', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (665, 'Ford', 'F350', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (666, 'Mazda', 'MX-5', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (667, 'Volkswagen', 'Jetta', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (668, 'Jeep', 'Wrangler', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (669, 'GMC', 'Savana 3500', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (670, 'GMC', '2500', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (671, 'Bentley', 'Continental Flying Spur', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (672, 'Ford', 'Fusion', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (673, 'Audi', 'Cabriolet', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (674, 'Kia', 'Sephia', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (675, 'Mercedes-Benz', '400E', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (676, 'BMW', '530', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (677, 'Kia', 'Sedona', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (678, 'Toyota', 'Sienna', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (679, 'Lamborghini', 'Countach', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (680, 'Morgan', 'Aero 8', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (681, 'Mercedes-Benz', 'CL-Class', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (682, 'Mercury', 'Lynx', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (683, 'GMC', 'Suburban 2500', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (684, 'Chevrolet', 'Suburban 1500', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (685, 'Dodge', 'Ram 1500 Club', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (686, 'Isuzu', 'Space', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (687, 'Pontiac', 'Bonneville', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (688, 'Pontiac', 'Aztek', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (689, 'Ford', 'Aspire', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (690, 'Porsche', '968', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (691, 'Dodge', 'D150', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (692, 'Buick', 'Electra', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (693, 'Honda', 'del Sol', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (694, 'Acura', 'TSX', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (695, 'Acura', 'MDX', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (696, 'Toyota', 'Venza', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (697, 'Nissan', 'Xterra', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (698, 'BMW', '5 Series', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (699, 'Toyota', 'Tacoma', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (700, 'MINI', 'Cooper', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (701, 'Chevrolet', 'Express 2500', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (702, 'Suzuki', 'Forenza', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (703, 'Chevrolet', 'Malibu', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (704, 'Honda', 'Prelude', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (705, 'Dodge', 'Dakota', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (706, 'Dodge', 'Ram 1500', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (707, 'Mercedes-Benz', '500E', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (708, 'Buick', 'Roadmaster', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (709, 'Ford', 'E250', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (710, 'Ford', 'Mustang', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (711, 'Audi', 'S8', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (712, 'Toyota', 'Paseo', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (713, 'Nissan', 'Sentra', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (714, 'Mercedes-Benz', 'W126', 1981);
insert into Car (id, CarMake, CarModel, CarYear) values (715, 'Austin', 'Mini', 1959);
insert into Car (id, CarMake, CarModel, CarYear) values (716, 'Chevrolet', 'Corvette', 1960);
insert into Car (id, CarMake, CarModel, CarYear) values (717, 'Infiniti', 'QX56', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (718, 'GMC', 'Suburban 2500', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (719, 'Acura', 'TL', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (720, 'Ford', 'Mustang', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (721, 'Toyota', 'Corolla', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (722, 'Pontiac', 'Bonneville', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (723, 'Infiniti', 'FX', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (724, 'Mitsubishi', 'Lancer', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (725, 'Honda', 'Accord', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (726, 'Ford', 'E150', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (727, 'Hummer', 'H2', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (728, 'Mercury', 'Sable', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (729, 'Buick', 'Century', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (730, 'Mercedes-Benz', 'S-Class', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (731, 'Mercedes-Benz', 'S-Class', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (732, 'Pontiac', 'Fiero', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (733, 'Plymouth', 'Grand Voyager', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (734, 'Land Rover', 'Discovery', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (735, 'Nissan', 'Xterra', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (736, 'Land Rover', 'LR3', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (737, 'Chevrolet', 'Silverado 2500', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (738, 'MINI', 'Clubman', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (739, 'Suzuki', 'Esteem', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (740, 'Volkswagen', 'Touareg 2', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (741, 'Cadillac', 'SRX', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (742, 'Chevrolet', 'Prizm', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (743, 'Chrysler', 'PT Cruiser', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (744, 'Bentley', 'Arnage', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (745, 'Toyota', 'Camry', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (746, 'Acura', 'ZDX', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (747, 'Lincoln', 'Town Car', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (748, 'Land Rover', 'Range Rover', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (749, 'Honda', 'Fit', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (750, 'Land Rover', 'Defender 110', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (751, 'Jeep', 'Liberty', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (752, 'Volkswagen', 'Touareg', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (753, 'Lincoln', 'Town Car', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (754, 'Acura', 'RL', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (755, 'Suzuki', 'SX4', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (756, 'Ford', 'Crown Victoria', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (757, 'Chevrolet', 'Corvette', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (758, 'Ford', 'Bronco', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (759, 'Buick', 'Rainier', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (760, 'Ford', 'E150', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (761, 'Lotus', 'Esprit', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (762, 'Audi', '5000S', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (763, 'Ford', 'Econoline E350', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (764, 'GMC', '1500 Club Coupe', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (765, 'Toyota', '4Runner', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (766, 'Hyundai', 'Sonata', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (767, 'Volvo', 'S60', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (768, 'Kia', 'Rio5', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (769, 'Dodge', 'D350 Club', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (770, 'Nissan', 'Frontier', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (771, 'Mercury', 'Tracer', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (772, 'Audi', 'Allroad', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (773, 'Buick', 'Somerset', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (774, 'Buick', 'Coachbuilder', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (775, 'Saturn', 'VUE', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (776, 'Austin', 'Mini', 1959);
insert into Car (id, CarMake, CarModel, CarYear) values (777, 'Lincoln', 'Town Car', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (778, 'Rolls-Royce', 'Phantom', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (779, 'Oldsmobile', 'Bravada', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (780, 'Pontiac', 'G5', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (781, 'Lincoln', 'Blackwood', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (782, 'Bentley', 'Continental GTC', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (783, 'Volvo', 'S60', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (784, 'GMC', 'Yukon', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (785, 'Nissan', 'Titan', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (786, 'Ford', 'Ranger', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (787, 'Suzuki', 'SJ 410', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (788, 'Mitsubishi', 'Lancer', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (789, 'Lincoln', 'Navigator', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (790, 'Honda', 'Element', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (791, 'Mercury', 'Sable', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (792, 'Mercury', 'Milan', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (793, 'Lotus', 'Esprit', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (794, 'Chrysler', 'Crossfire', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (795, 'Nissan', 'Armada', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (796, 'Jeep', 'Grand Cherokee', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (797, 'Subaru', 'SVX', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (798, 'Acura', 'RDX', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (799, 'Ford', 'E150', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (800, 'Kia', 'Forte', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (801, 'Mercury', 'Villager', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (802, 'Lexus', 'ES', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (803, 'Jeep', 'Cherokee', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (804, 'Buick', 'Somerset', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (805, 'Audi', 'A4', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (806, 'Toyota', 'Tacoma', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (807, 'Chevrolet', 'Avalanche 1500', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (808, 'GMC', 'Savana 2500', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (809, 'Hummer', 'H2', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (810, 'Mazda', 'MPV', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (811, 'Volvo', 'S60', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (812, 'Toyota', 'FJ Cruiser', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (813, 'Honda', 'Pilot', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (814, 'Lexus', 'RX', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (815, 'Audi', 'V8', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (816, 'Honda', 'Pilot', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (817, 'Buick', 'Century', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (818, 'Eagle', 'Talon', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (819, 'Volkswagen', 'Corrado', 1990);
insert into Car (id, CarMake, CarModel, CarYear) values (820, 'Dodge', 'Dakota', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (821, 'BMW', 'M5', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (822, 'Mitsubishi', 'Endeavor', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (823, 'Dodge', 'Stratus', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (824, 'Volvo', '850', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (825, 'Saturn', 'S-Series', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (826, 'GMC', '1500 Club Coupe', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (827, 'Nissan', 'Quest', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (828, 'Toyota', 'Highlander', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (829, 'Land Rover', 'Range Rover Sport', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (830, 'Toyota', 'Supra', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (831, 'Nissan', 'Altima', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (832, 'Dodge', 'Ram 2500 Club', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (833, 'Isuzu', 'Trooper', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (834, 'Ford', 'Festiva', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (835, 'GMC', 'Sierra 1500', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (836, 'Honda', 'Civic', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (837, 'Plymouth', 'Voyager', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (838, 'Mitsubishi', 'Pajero', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (839, 'Ford', 'F350', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (840, 'Volkswagen', 'Rabbit', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (841, 'Ford', 'EXP', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (842, 'Ford', 'F-Series', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (843, 'Volvo', 'XC70', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (844, 'Subaru', 'Legacy', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (845, 'Austin', 'Mini Cooper', 1961);
insert into Car (id, CarMake, CarModel, CarYear) values (846, 'Chevrolet', 'Avalanche 1500', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (847, 'Chevrolet', 'Silverado 3500', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (848, 'Dodge', 'Ram Van 3500', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (849, 'Volkswagen', 'Jetta', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (850, 'Ford', 'Explorer', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (851, 'Mercedes-Benz', 'E-Class', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (852, 'Ram', '1500', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (853, 'Oldsmobile', 'Achieva', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (854, 'Infiniti', 'G', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (855, 'Pontiac', 'Bonneville', 1964);
insert into Car (id, CarMake, CarModel, CarYear) values (856, 'Chevrolet', 'Corvair', 1960);
insert into Car (id, CarMake, CarModel, CarYear) values (857, 'Ford', 'Flex', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (858, 'GMC', 'Vandura 3500', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (859, 'Chevrolet', 'Tracker', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (860, 'Mitsubishi', 'Endeavor', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (861, 'Isuzu', 'Oasis', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (862, 'Lincoln', 'Town Car', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (863, 'Audi', 'A6', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (864, 'Toyota', '4Runner', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (865, 'Mercedes-Benz', 'CLK-Class', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (866, 'Dodge', 'Viper', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (867, 'Oldsmobile', 'Cutlass', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (868, 'Pontiac', 'GTO', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (869, 'GMC', 'Sierra 1500', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (870, 'GMC', 'Sonoma', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (871, 'Pontiac', 'Bonneville', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (872, 'Suzuki', 'Swift', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (873, 'Nissan', 'Sentra', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (874, 'Volkswagen', 'Scirocco', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (875, 'BMW', '7 Series', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (876, 'Volkswagen', 'Golf', 1988);
insert into Car (id, CarMake, CarModel, CarYear) values (877, 'Oldsmobile', 'Cutlass Cruiser', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (878, 'Audi', 'Coupe GT', 1987);
insert into Car (id, CarMake, CarModel, CarYear) values (879, 'Dodge', 'Intrepid', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (880, 'Dodge', 'Dakota', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (881, 'GMC', 'Sierra 1500', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (882, 'Toyota', 'Venza', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (883, 'Lincoln', 'Navigator', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (884, 'Smart', 'Fortwo', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (885, 'Ford', 'Bronco', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (886, 'Pontiac', 'Grand Prix', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (887, 'Ford', 'E250', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (888, 'Buick', 'LeSabre', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (889, 'Dodge', 'Dakota', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (890, 'Isuzu', 'Rodeo', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (891, 'Dodge', 'Monaco', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (892, 'Infiniti', 'QX', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (893, 'Mazda', 'MX-5', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (894, 'Dodge', 'Ram Van 1500', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (895, 'Saturn', 'Ion', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (896, 'Plymouth', 'Breeze', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (897, 'Maybach', '62', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (898, 'Chevrolet', 'Sportvan G10', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (899, 'Mercury', 'Mountaineer', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (900, 'Plymouth', 'Neon', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (901, 'Kia', 'Rondo', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (902, 'Cadillac', 'XLR', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (903, 'Ford', 'F150', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (904, 'Ford', 'Econoline E250', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (905, 'Audi', 'A4', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (906, 'Ford', 'Explorer', 2013);
insert into Car (id, CarMake, CarModel, CarYear) values (907, 'Subaru', 'Impreza', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (908, 'Mitsubishi', 'Montero Sport', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (909, 'Ford', 'F350', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (910, 'Volvo', '940', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (911, 'BMW', '3 Series', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (912, 'Isuzu', 'Hombre Space', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (913, 'Dodge', 'Viper RT/10', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (914, 'Lincoln', 'Navigator', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (915, 'Buick', 'Regal', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (916, 'Toyota', 'Sienna', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (917, 'Mitsubishi', 'Truck', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (918, 'Mercedes-Benz', 'SLK-Class', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (919, 'Chevrolet', 'Silverado 2500', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (920, 'Chevrolet', 'APV', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (921, 'Audi', 'TT', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (922, 'Honda', 'CR-V', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (923, 'BMW', 'X5', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (924, 'Ford', 'Expedition', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (925, 'Mitsubishi', 'Galant', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (926, 'Volvo', 'V40', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (927, 'Mercury', 'Mariner', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (928, 'Hyundai', 'Veracruz', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (929, 'Chevrolet', 'Suburban 1500', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (930, 'Chevrolet', 'Avalanche', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (931, 'Cadillac', 'Escalade ESV', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (932, 'Jeep', 'Cherokee', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (933, 'Cadillac', 'XLR', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (934, 'Lexus', 'LS', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (935, 'Chevrolet', '3500', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (936, 'Ford', 'Aerostar', 1986);
insert into Car (id, CarMake, CarModel, CarYear) values (937, 'Chrysler', 'Pacifica', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (938, 'Porsche', '944', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (939, 'Rolls-Royce', 'Phantom', 2011);
insert into Car (id, CarMake, CarModel, CarYear) values (940, 'BMW', '530', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (941, 'Ford', 'Thunderbird', 1967);
insert into Car (id, CarMake, CarModel, CarYear) values (942, 'Mercedes-Benz', 'C-Class', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (943, 'Chevrolet', 'Lumina', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (944, 'BMW', '7 Series', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (945, 'Chevrolet', 'Express 2500', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (946, 'Hyundai', 'Azera', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (947, 'Nissan', 'Rogue', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (948, 'Hyundai', 'Genesis Coupe', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (949, 'Mazda', 'B-Series', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (950, 'Lincoln', 'Navigator L', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (951, 'GMC', '3500 Club Coupe', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (952, 'Volvo', '740', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (953, 'Mazda', 'MPV', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (954, 'Kia', 'Sorento', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (955, 'Lexus', 'GS', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (956, 'Volkswagen', 'Scirocco', 1984);
insert into Car (id, CarMake, CarModel, CarYear) values (957, 'Lincoln', 'Navigator L', 2007);
insert into Car (id, CarMake, CarModel, CarYear) values (958, 'Audi', 'S8', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (959, 'Mitsubishi', 'Eclipse', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (960, 'Honda', 'Accord', 1985);
insert into Car (id, CarMake, CarModel, CarYear) values (961, 'GMC', 'Safari', 2000);
insert into Car (id, CarMake, CarModel, CarYear) values (962, 'BMW', '3 Series', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (963, 'Chrysler', 'Sebring', 2004);
insert into Car (id, CarMake, CarModel, CarYear) values (964, 'Hyundai', 'Elantra', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (965, 'GMC', '1500', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (966, 'Chevrolet', 'Corsica', 1993);
insert into Car (id, CarMake, CarModel, CarYear) values (967, 'Mercedes-Benz', 'S-Class', 1996);
insert into Car (id, CarMake, CarModel, CarYear) values (968, 'Chevrolet', 'Corvette', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (969, 'Chevrolet', 'Tahoe', 2013);
insert into Car (id, CarMake, CarModel, CarYear) values (970, 'Volvo', 'XC90', 2005);
insert into Car (id, CarMake, CarModel, CarYear) values (971, 'Chevrolet', 'Corvair', 1960);
insert into Car (id, CarMake, CarModel, CarYear) values (972, 'Ford', 'F-Series', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (973, 'Honda', 'Accord', 1991);
insert into Car (id, CarMake, CarModel, CarYear) values (974, 'Mitsubishi', '3000GT', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (975, 'Toyota', 'TundraMax', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (976, 'Nissan', 'Pathfinder', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (977, 'Suzuki', 'Vitara', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (978, 'Toyota', 'Highlander', 2001);
insert into Car (id, CarMake, CarModel, CarYear) values (979, 'Mercedes-Benz', 'M-Class', 1998);
insert into Car (id, CarMake, CarModel, CarYear) values (980, 'Ford', 'LTD Crown Victoria', 1989);
insert into Car (id, CarMake, CarModel, CarYear) values (981, 'Honda', 'Pilot', 2006);
insert into Car (id, CarMake, CarModel, CarYear) values (982, 'Dodge', 'Ram 2500', 1994);
insert into Car (id, CarMake, CarModel, CarYear) values (983, 'Toyota', 'Corolla', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (984, 'BMW', '5 Series', 2003);
insert into Car (id, CarMake, CarModel, CarYear) values (985, 'Oldsmobile', 'Achieva', 1992);
insert into Car (id, CarMake, CarModel, CarYear) values (986, 'Mercury', 'Grand Marquis', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (987, 'Nissan', 'Quest', 2012);
insert into Car (id, CarMake, CarModel, CarYear) values (988, 'Honda', 'Civic', 2008);
insert into Car (id, CarMake, CarModel, CarYear) values (989, 'Chevrolet', 'Astro', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (990, 'Mercedes-Benz', 'CL-Class', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (991, 'Nissan', 'Maxima', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (992, 'Hyundai', 'Tucson', 2009);
insert into Car (id, CarMake, CarModel, CarYear) values (993, 'Chevrolet', 'Silverado 1500', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (994, 'Dodge', 'Grand Caravan', 2010);
insert into Car (id, CarMake, CarModel, CarYear) values (995, 'Plymouth', 'Roadrunner', 1969);
insert into Car (id, CarMake, CarModel, CarYear) values (996, 'Chrysler', 'Town & Country', 1995);
insert into Car (id, CarMake, CarModel, CarYear) values (997, 'BMW', '525', 2002);
insert into Car (id, CarMake, CarModel, CarYear) values (998, 'Lincoln', 'Continental', 1997);
insert into Car (id, CarMake, CarModel, CarYear) values (999, 'Mercury', 'Mystique', 1999);
insert into Car (id, CarMake, CarModel, CarYear) values (1000, 'Honda', 'Accord', 1996);
