create table School (
	id INT,
	School VARCHAR(50)
);
insert into School (id, School) values (1, 'Chongju University');
insert into School (id, School) values (2, 'Institute of Management and Business Technology');
insert into School (id, School) values (3, 'Rosemont College');
insert into School (id, School) values (4, 'Islamic Azad University, Hamedan');
insert into School (id, School) values (5, 'Karaganda State Technical University');
insert into School (id, School) values (6, 'DeVry Institute of Technology, Phoenix');
insert into School (id, School) values (7, 'Universidade Potiguar');
insert into School (id, School) values (8, 'Institut National des Télécommunications');
insert into School (id, School) values (9, 'Rostov State Medical University');
insert into School (id, School) values (10, 'Fachhochschule Wiener Neustadt');
insert into School (id, School) values (11, 'Dares Salaam Institute of Technology');
insert into School (id, School) values (12, 'Sambalpur University');
insert into School (id, School) values (13, 'Hamline University');
insert into School (id, School) values (14, 'State University of New York College at Plattsburgh');
insert into School (id, School) values (15, 'Napier University');
insert into School (id, School) values (16, 'Wartburg College');
insert into School (id, School) values (17, 'Bindura University of Science Education');
insert into School (id, School) values (18, 'Oklahoma State University');
insert into School (id, School) values (19, 'Nagano University');
insert into School (id, School) values (20, 'Limestone College');
insert into School (id, School) values (21, 'Bryan College');
insert into School (id, School) values (22, 'City University Programs in Bulgaria ');
insert into School (id, School) values (23, 'Principia College');
insert into School (id, School) values (24, 'St. Thomas University');
insert into School (id, School) values (25, 'Ecole Nationale Supérieure de Chimie de Toulouse');
insert into School (id, School) values (26, 'Guru Gobind Singh Indraprastha University');
insert into School (id, School) values (27, 'Stillman College');
insert into School (id, School) values (28, 'Hokkaido Tokai University');
insert into School (id, School) values (29, 'University of New Brunswick');
insert into School (id, School) values (30, 'Huazhong University of Science and Technology');
insert into School (id, School) values (31, 'Marij State University');
insert into School (id, School) values (32, 'Augustana College');
insert into School (id, School) values (33, 'DCT International Hotel & Business Management School');
insert into School (id, School) values (34, 'La Roche College');
insert into School (id, School) values (35, 'Katholieke Hogeschool Kempen');
insert into School (id, School) values (36, 'University of Iasi');
insert into School (id, School) values (37, 'Huaqiao University Quanzhuo');
insert into School (id, School) values (38, 'Hiroshima University');
insert into School (id, School) values (39, 'Erasmushogeschool Brussel');
insert into School (id, School) values (40, 'South University of Science and Technology of China ');
insert into School (id, School) values (41, 'Osaka University of Education');
insert into School (id, School) values (42, 'Guilford College');
insert into School (id, School) values (43, 'Hochschule Mittweida (FH)');
insert into School (id, School) values (44, 'Indian Institute of Technology, Delhi');
insert into School (id, School) values (45, 'National University of Arts');
insert into School (id, School) values (46, 'Université Sorbonne-Nouvelle (Paris III)');
insert into School (id, School) values (47, 'Charter Oak State College');
insert into School (id, School) values (48, 'Jamestown College');
insert into School (id, School) values (49, 'Shandong Agricultural University');
insert into School (id, School) values (50, 'Universitas Ahmad Dahlan');
insert into School (id, School) values (51, 'Sultan Abdul Halim Muadzam Shah Polytechnic');
insert into School (id, School) values (52, 'Georgia Southwestern University');
insert into School (id, School) values (53, 'Inner Mongolia University');
insert into School (id, School) values (54, 'Florida Gulf Coast University');
insert into School (id, School) values (55, 'Universidad de Almería');
insert into School (id, School) values (56, 'Ritsumeikan Asia Pacific University');
insert into School (id, School) values (57, 'Moscow State University of Geodesy and Cartography');
insert into School (id, School) values (58, 'Tyumen State University of Gas and Oil');
insert into School (id, School) values (59, 'University of the City of Manila');
insert into School (id, School) values (60, 'Excelsior College');
insert into School (id, School) values (61, 'Toyo Gakuen University');
insert into School (id, School) values (62, 'Cambodian Mekong University');
insert into School (id, School) values (63, 'Victoria University');
insert into School (id, School) values (64, 'Aichi Prefectural University of Fine Arts & Music');
insert into School (id, School) values (65, 'Kurukshetra University');
insert into School (id, School) values (66, 'Mahatma Gandhi University, Kerala');
insert into School (id, School) values (67, 'Wilberforce University');
insert into School (id, School) values (68, 'Hitotsubashi University');
insert into School (id, School) values (69, 'Gdynia Maritime Academy');
insert into School (id, School) values (70, 'Universitas 17 Agustus 1945 Jakarta');
insert into School (id, School) values (71, 'Ecole Nationale Supérieure de l''Electronique et de ses Applications');
insert into School (id, School) values (72, 'Universitas Amir Hamzah');
insert into School (id, School) values (73, 'Institute of Management and Business Technology');
insert into School (id, School) values (74, 'Technical University of Timisoara');
insert into School (id, School) values (75, 'New Jersey City University');
insert into School (id, School) values (76, 'International Islamic College');
insert into School (id, School) values (77, 'Shuchiin College');
insert into School (id, School) values (78, 'Keiai University');
insert into School (id, School) values (79, 'University of Nottingham');
insert into School (id, School) values (80, 'Universidad Politécnica de El Salvador');
insert into School (id, School) values (81, 'St. Joseph University Beirut');
insert into School (id, School) values (82, 'Narendra Deva University of Agriculture and Technology');
insert into School (id, School) values (83, 'University of Nis');
insert into School (id, School) values (84, 'Spring Arbor College');
insert into School (id, School) values (85, 'University of Massachusetts at Boston');
insert into School (id, School) values (86, 'University College of the Cariboo');
insert into School (id, School) values (87, 'Universidad Diego Portales');
insert into School (id, School) values (88, 'Stevens Institute of Technology');
insert into School (id, School) values (89, 'University of Wolverhampton');
insert into School (id, School) values (90, 'Universidad Central del Caribe');
insert into School (id, School) values (91, 'Technical University of Denmark');
insert into School (id, School) values (92, 'Philosophisch-Theologische Hochschule SVD Sankt Augustin');
insert into School (id, School) values (93, 'ITT Technical Institute Fort Wayne');
insert into School (id, School) values (94, 'Edogawa University');
insert into School (id, School) values (95, 'Moscow State Institute of International Relations MFA Russia (MGIMO-University)');
insert into School (id, School) values (96, 'Göteborg University');
insert into School (id, School) values (97, 'Antioch University');
insert into School (id, School) values (98, 'Shih Hsin University');
insert into School (id, School) values (99, 'Wuhan University School of Medicine');
insert into School (id, School) values (100, 'Université Victor Segalen (Bordeaux II)');
insert into School (id, School) values (101, 'Spartan University of Health Sciences');
insert into School (id, School) values (102, 'Indiana Wesleyan University');
insert into School (id, School) values (103, 'Wollega University');
insert into School (id, School) values (104, 'Universidad Amazonica de Pando');
insert into School (id, School) values (105, 'South Dakota School of Mines and Technology');
insert into School (id, School) values (106, 'Université de Montréal');
insert into School (id, School) values (107, 'Second University of Naples');
insert into School (id, School) values (108, 'Semyung University');
insert into School (id, School) values (109, 'Mohammad Ali Jinnah University, Karachi');
insert into School (id, School) values (110, 'Friedrich-Schiller Universität Jena');
insert into School (id, School) values (111, 'Harbin University of Science and Technology');
insert into School (id, School) values (112, 'Oklahoma Panhandle State University');
insert into School (id, School) values (113, 'Kaya University');
insert into School (id, School) values (114, 'Pomona College');
insert into School (id, School) values (115, 'Institut Teknologi Sepuluh Nopember');
insert into School (id, School) values (116, 'Changsha Railway University');
insert into School (id, School) values (117, 'Pontificia Università S. Tommaso');
insert into School (id, School) values (118, 'Instituto Nacional de Educación Física "General Manuel Belgrano"');
insert into School (id, School) values (119, 'National Chiayi University');
insert into School (id, School) values (120, 'University of Cincinnati');
insert into School (id, School) values (121, 'University of Swaziland');
insert into School (id, School) values (122, 'Sami Shamoon College of Engineering');
insert into School (id, School) values (123, 'Universidad Iberoamericana');
insert into School (id, School) values (124, 'Evangelische Fachhochschule Reutlingen-Ludwigsburg, Hochschule für Soziale Arbeit, Religionspädagogik und Diakonie');
insert into School (id, School) values (125, 'Makerere University');
insert into School (id, School) values (126, 'Kyoto Tachibana Women''s University');
insert into School (id, School) values (127, 'Iwate Medical University');
insert into School (id, School) values (128, 'University of Michigan - Ann Arbor');
insert into School (id, School) values (129, 'Notre Dame College');
insert into School (id, School) values (130, 'Universidad de Holguín');
insert into School (id, School) values (131, 'Notre Dame College of Ohio');
insert into School (id, School) values (132, 'Japanese Red Cross College of Nursing');
insert into School (id, School) values (133, 'Sapporo University');
insert into School (id, School) values (134, 'Karunya Institute Of Technology ( Deemed University)');
insert into School (id, School) values (135, 'Sacred Heart University');
insert into School (id, School) values (136, 'College of the Rockies');
insert into School (id, School) values (137, 'Troy University, Dothan');
insert into School (id, School) values (138, 'Le Moyne-Owen College');
insert into School (id, School) values (139, 'Jacksonville University');
insert into School (id, School) values (140, 'Instituto Politécnico de Coimbra');
insert into School (id, School) values (141, 'Meiji Gakuin University');
insert into School (id, School) values (142, 'Bishkek Humanities University');
insert into School (id, School) values (143, 'Université de Douala');
insert into School (id, School) values (144, 'Nanjing University of Posts and Telecommunications');
insert into School (id, School) values (145, 'Józef Tyszkiewicz College of Business and Computer Science in Bielsko-Biala');
insert into School (id, School) values (146, 'Tongji University');
insert into School (id, School) values (147, 'Al Imam Al-Ouzai University');
insert into School (id, School) values (148, 'Hogeschool voor Wetenschap en Kunst (VLEKHO), Brussel');
insert into School (id, School) values (149, 'Universidad Católica de Honduras');
insert into School (id, School) values (150, 'Institute of Teachers Education, Sultan Mizan');
insert into School (id, School) values (151, 'Osaka Women''s University');
insert into School (id, School) values (152, 'Katowice School of Economics');
insert into School (id, School) values (153, 'Universidade Estadual do Norte Fluminense');
insert into School (id, School) values (154, 'Technological Education Institute of Thessaloniki');
insert into School (id, School) values (155, 'National American University');
insert into School (id, School) values (156, 'Technical University of Zielona Gora');
insert into School (id, School) values (157, 'International College');
insert into School (id, School) values (158, 'Arab American University - Jenin');
insert into School (id, School) values (159, 'Institut Teknologi Bandung');
insert into School (id, School) values (160, 'Surgut State University');
insert into School (id, School) values (161, 'University of Sussex');
insert into School (id, School) values (162, 'Universidad Central de Las Villas');
insert into School (id, School) values (163, 'East Kazakstan State Technical University');
insert into School (id, School) values (164, 'Institute of Teachers Education, Sarawak');
insert into School (id, School) values (165, 'Africa University');
insert into School (id, School) values (166, 'Wayne State College');
insert into School (id, School) values (167, 'National Academy for Physical Education and Sports Bucharest');
insert into School (id, School) values (168, 'University of Applied Sciences Chur');
insert into School (id, School) values (169, 'Université d''Antananarivo');
insert into School (id, School) values (170, 'Université Chrétienne Bilingue du Congo');
insert into School (id, School) values (171, 'Molloy College');
insert into School (id, School) values (172, 'Universitas Dian Nuswantoro');
insert into School (id, School) values (173, 'American University in Bulgaria');
insert into School (id, School) values (174, 'Frostburg State University');
insert into School (id, School) values (175, 'University of Bedfordshire');
insert into School (id, School) values (176, 'VanderCook College of Music');
insert into School (id, School) values (177, 'University of Central Europe in Skalica');
insert into School (id, School) values (178, 'Logistics Engineering University of PLA');
insert into School (id, School) values (179, 'Zawiya Academy');
insert into School (id, School) values (180, 'Institute of Social Studies');
insert into School (id, School) values (181, 'City University Programs in Bulgaria ');
insert into School (id, School) values (182, 'Rasmussen College, Florida Campuses');
insert into School (id, School) values (183, 'International College of the Cayman Islands');
insert into School (id, School) values (184, 'Ufa State Institute of Arts');
insert into School (id, School) values (185, 'School for International Training');
insert into School (id, School) values (186, 'Don State Technical University');
insert into School (id, School) values (187, 'State University of Aerospace Technologies');
insert into School (id, School) values (188, 'University of Tromsø');
insert into School (id, School) values (189, 'University of New Brunswick, Saint John');
insert into School (id, School) values (190, 'Universidad Gabriela Mistral');
insert into School (id, School) values (191, 'Ozyegin University');
insert into School (id, School) values (192, 'Chongqing University of Communications');
insert into School (id, School) values (193, 'Gujarat University Ahmedabad');
insert into School (id, School) values (194, 'Ecole Nationale Supérieure des Mines d''Alès');
insert into School (id, School) values (195, 'Ecole d''Ingénieurs en Informatique pour l''Industrie');
insert into School (id, School) values (196, 'Theologische Fakultät Paderborn');
insert into School (id, School) values (197, 'Ecole des Hautes Etudes en Gestion Informatique et Communication');
insert into School (id, School) values (198, 'Atlanta Christian College');
insert into School (id, School) values (199, 'Universiti Sultan Zainal Abidin');
insert into School (id, School) values (200, 'Europa Fachhochschule Fresenius');
insert into School (id, School) values (201, 'Universidad del Tepeyac');
insert into School (id, School) values (202, 'Ashikaga Institute of Technology');
insert into School (id, School) values (203, 'University of Chemical Technology and Metallurgy');
insert into School (id, School) values (204, 'University of Tennessee - Memphis');
insert into School (id, School) values (205, 'Heidelberg College');
insert into School (id, School) values (206, 'Miyazaki Municipal University');
insert into School (id, School) values (207, 'Universidad Católica de Valencia');
insert into School (id, School) values (208, 'Universidad Tecnológica América');
insert into School (id, School) values (209, 'Tibet Tibetan Medical College');
insert into School (id, School) values (210, 'University of South Carolina - Beaufort');
insert into School (id, School) values (211, 'Escuela Politécnica de Chimborazo');
insert into School (id, School) values (212, 'Ecole Supérieure de Commerce de Bordeaux');
insert into School (id, School) values (213, 'Universidade de Tocantins');
insert into School (id, School) values (214, 'Delijan Payame Noor University');
insert into School (id, School) values (215, 'Prince Mohammad Bin Fahd University');
insert into School (id, School) values (216, 'Lakshmibai National Institute of Physical Education');
insert into School (id, School) values (217, 'Hochschule für Politik (HFP)');
insert into School (id, School) values (218, 'Clark University');
insert into School (id, School) values (219, 'Esztergom Theological College');
insert into School (id, School) values (220, 'University of Dammam');
insert into School (id, School) values (221, 'Philosophisch-Theologische Hochschule der Salesianer Don Boscos');
insert into School (id, School) values (222, 'Elmhurst College');
insert into School (id, School) values (223, 'Tokyo Dental College');
insert into School (id, School) values (224, 'Fayetteville State University');
insert into School (id, School) values (225, 'Birla Institute of Technology, Ranchi');
insert into School (id, School) values (226, 'Nnamdi Azikiwe University');
insert into School (id, School) values (227, 'Gulf University for Science and Technology');
insert into School (id, School) values (228, 'Pontificia Università della Santa Croce');
insert into School (id, School) values (229, 'Universidad Católica de La Plata');
insert into School (id, School) values (230, 'Instituto Universitario Aeronáutico');
insert into School (id, School) values (231, 'Kenya Medical Training College');
insert into School (id, School) values (232, 'Florida Gulf Coast University');
insert into School (id, School) values (233, 'University of Kalyani');
insert into School (id, School) values (234, 'Fachhochschule JOANNEUM');
insert into School (id, School) values (235, 'St. Petersburg State Mining Institute (Technical University)');
insert into School (id, School) values (236, 'Hajvery University Lahore for Women');
insert into School (id, School) values (237, 'Xuzhou Normal University');
insert into School (id, School) values (238, 'Dav University');
insert into School (id, School) values (239, 'St. Vincent College');
insert into School (id, School) values (240, 'Hope Africa University');
insert into School (id, School) values (241, 'Universidad Católica de Córdoba');
insert into School (id, School) values (242, 'Saigon University');
insert into School (id, School) values (243, 'Hesser College');
insert into School (id, School) values (244, 'Shanghai Ouhua Vocational Technical College');
insert into School (id, School) values (245, 'Semyung University');
insert into School (id, School) values (246, 'Eastern Virginia Medical School');
insert into School (id, School) values (247, 'Evangelische Fachhochschule Darmstadt');
insert into School (id, School) values (248, 'Virginia Commonwealth University');
insert into School (id, School) values (249, 'University of Alaska - Fairbanks');
insert into School (id, School) values (250, 'Pontificia Università Lateranense');
insert into School (id, School) values (251, 'North Greenville College');
insert into School (id, School) values (252, 'Université de Kairouan');
insert into School (id, School) values (253, 'Visva-Bharati University');
insert into School (id, School) values (254, 'Wawasan Open University');
insert into School (id, School) values (255, 'Urmia University');
insert into School (id, School) values (256, 'Université Mohammed Ier');
insert into School (id, School) values (257, 'University of Burao');
insert into School (id, School) values (258, 'Rak Medical & Health Sciences University');
insert into School (id, School) values (259, 'Vietnam National University Ho Chi Minh City');
insert into School (id, School) values (260, 'Federal University of Technology, Yola');
insert into School (id, School) values (261, 'Bule Hora  University');
insert into School (id, School) values (262, 'International Medical University');
insert into School (id, School) values (263, 'Tibet University of Nationalities');
insert into School (id, School) values (264, 'University of Fribourg');
insert into School (id, School) values (265, 'Christchurch Polytechnic Institute of Technology');
insert into School (id, School) values (266, 'Instituto Tecnológico de León');
insert into School (id, School) values (267, 'Tohoku Fukushi University');
insert into School (id, School) values (268, 'Walsh University');
insert into School (id, School) values (269, 'Mills Grae University');
insert into School (id, School) values (270, 'Boise State University');
insert into School (id, School) values (271, 'Nanyang Technological University');
insert into School (id, School) values (272, 'Universidade do Amazonas');
insert into School (id, School) values (273, 'William Jewell College');
insert into School (id, School) values (274, 'University of Italian Studies for Foreigners of Perugia');
insert into School (id, School) values (275, 'King''s College');
insert into School (id, School) values (276, 'Moi University');
insert into School (id, School) values (277, 'Universidad Autonoma de Chiriqui');
insert into School (id, School) values (278, 'Khabarovsk State University of Technology');
insert into School (id, School) values (279, 'Universitas Yarsi');
insert into School (id, School) values (280, 'University of Canberra');
insert into School (id, School) values (281, 'China Three Gorges University');
insert into School (id, School) values (282, 'University of Kuopio');
insert into School (id, School) values (283, 'Universidad de la Integración de las Americas (UNIDAD)');
insert into School (id, School) values (284, 'Lamar University');
insert into School (id, School) values (285, 'Brunel University Uxbridge');
insert into School (id, School) values (286, 'Laurentian University of Sudbury');
insert into School (id, School) values (287, 'Fachhochschule Stralsund');
insert into School (id, School) values (288, 'Gansu Agricultural University');
insert into School (id, School) values (289, 'Khulna University of Engineering And Technology');
insert into School (id, School) values (290, 'Balochistan University of Information Technology & Management Sciences ');
insert into School (id, School) values (291, 'Christ University');
insert into School (id, School) values (292, 'Iwate Prefectural University');
insert into School (id, School) values (293, 'Universidad del Valle de México');
insert into School (id, School) values (294, 'Aichi Sangyo University');
insert into School (id, School) values (295, 'Fundação Educacional de Ituverava');
insert into School (id, School) values (296, 'Texas A&M University - Galveston');
insert into School (id, School) values (297, 'Tambov State Technical University');
insert into School (id, School) values (298, 'Zagazig University');
insert into School (id, School) values (299, 'Fachhochschule Regensburg');
insert into School (id, School) values (300, 'Universidad Argentina de la Empresa');
insert into School (id, School) values (301, 'Lindenwood University');
insert into School (id, School) values (302, 'Jawaharlal Nehru Technological University');
insert into School (id, School) values (303, 'University of Maine, Orono');
insert into School (id, School) values (304, 'Baha''i Institute for Higher Education');
insert into School (id, School) values (305, 'Loyola University New Orleans');
insert into School (id, School) values (306, 'Taj International College');
insert into School (id, School) values (307, 'Illinois College');
insert into School (id, School) values (308, 'Divine Word College');
insert into School (id, School) values (309, 'Dutch Delta University');
insert into School (id, School) values (310, 'Nigde University');
insert into School (id, School) values (311, 'Montreat College');
insert into School (id, School) values (312, 'University of Medicine and Pharmacy of Timisoara');
insert into School (id, School) values (313, 'Internationle Akademie für Philosophie');
insert into School (id, School) values (314, 'University of Delhi');
insert into School (id, School) values (315, 'Sumgait State University');
insert into School (id, School) values (316, 'Universidad de Guadalajara');
insert into School (id, School) values (317, 'Instituto Politécnico de Lisboa');
insert into School (id, School) values (318, 'Universidad Católica del Norte');
insert into School (id, School) values (319, 'Universitas Ahmad Dahlan');
insert into School (id, School) values (320, 'Regent University');
insert into School (id, School) values (321, 'Necmettin Erbakan University');
insert into School (id, School) values (322, 'Poole Gakuin University');
insert into School (id, School) values (323, 'Rosemont College');
insert into School (id, School) values (324, 'Johnson County Community College');
insert into School (id, School) values (325, 'Institute of Management Sciences, Peshawar');
insert into School (id, School) values (326, 'University of Aizu');
insert into School (id, School) values (327, 'International Banking Institute, St. Petersburg');
insert into School (id, School) values (328, 'Universidad Autónoma de Coahuila');
insert into School (id, School) values (329, 'Balochistan University of Information Technology & Management Sciences ');
insert into School (id, School) values (330, 'Technological University (Maubin)');
insert into School (id, School) values (331, 'Carroll College Waukesha');
insert into School (id, School) values (332, 'Sichuan Normal University');
insert into School (id, School) values (333, 'Florida Gulf Coast University');
insert into School (id, School) values (334, 'Randolph-Macon Woman''s College');
insert into School (id, School) values (335, 'University of Huddersfield');
insert into School (id, School) values (336, 'Northwestern Oklahoma State University');
insert into School (id, School) values (337, 'Utsunomiya University');
insert into School (id, School) values (338, 'Hiroshima City University');
insert into School (id, School) values (339, 'Purdue University North Central');
insert into School (id, School) values (340, 'Aga Khan University');
insert into School (id, School) values (341, 'Comenius University in Bratislava');
insert into School (id, School) values (342, 'Universidade do Sagrado Coração');
insert into School (id, School) values (343, 'Catholic Theological Union');
insert into School (id, School) values (344, 'Herat University');
insert into School (id, School) values (345, 'Fashion Institute of New York');
insert into School (id, School) values (346, 'Ukrainian Academy of Pharmacy');
insert into School (id, School) values (347, 'California State University, Monterey Bay');
insert into School (id, School) values (348, 'Instituto Tecnologico de Minatitlan');
insert into School (id, School) values (349, 'Ludong University');
insert into School (id, School) values (350, 'Universidad Autónoma Gabriel René Moreno');
insert into School (id, School) values (351, 'Fachhochschule Osnabrück');
insert into School (id, School) values (352, 'Université du Havre');
insert into School (id, School) values (353, 'Istanbul Ticaret University');
insert into School (id, School) values (354, 'Taoist College Singapore');
insert into School (id, School) values (355, 'Université Vincennes Saint-Denis (Paris VIII)');
insert into School (id, School) values (356, 'University of Social Welfare and Rehabilitation Scinences');
insert into School (id, School) values (357, 'Université Catholique de Lille');
insert into School (id, School) values (358, 'Tomas Bata University in Zlin');
insert into School (id, School) values (359, 'Universidad La Salle');
insert into School (id, School) values (360, 'Rezekne Higher School');
insert into School (id, School) values (361, 'National Academy of Music "Pantcho Vladigerov"');
insert into School (id, School) values (362, 'University of Saint La Salle');
insert into School (id, School) values (363, 'University of Holy Quran and Islamic Siences');
insert into School (id, School) values (364, 'Shiga University');
insert into School (id, School) values (365, 'Bahauddin Zakariya University, Multan');
insert into School (id, School) values (366, 'Damanhour University');
insert into School (id, School) values (367, 'Mongolian National University');
insert into School (id, School) values (368, 'Salahddin University (Kurdistan Region)');
insert into School (id, School) values (369, 'GC University');
insert into School (id, School) values (370, 'Ecole Française d''Electronique et d''Informatique');
insert into School (id, School) values (371, 'Université du Droit et de la Sante (Lille II)');
insert into School (id, School) values (372, 'Volgograd State Academy of Physical Education');
insert into School (id, School) values (373, 'East Kazakstan State Technical University');
insert into School (id, School) values (374, 'Asbury College');
insert into School (id, School) values (375, 'Université du Québec en Abitibi-Témiscamingue');
insert into School (id, School) values (376, 'University of Dubuque');
insert into School (id, School) values (377, 'Fundación Universitaria Luis Amigó');
insert into School (id, School) values (378, 'Riara University School of Business and Law');
insert into School (id, School) values (379, 'Kyrgyz State Technical University');
insert into School (id, School) values (380, 'Open University of Sudan (OUS)');
insert into School (id, School) values (381, 'College of William and Mary');
insert into School (id, School) values (382, 'Prague College');
insert into School (id, School) values (383, 'University of Tasmania');
insert into School (id, School) values (384, 'Azerbaijan National Conservatorie');
insert into School (id, School) values (385, 'Warner Pacific College');
insert into School (id, School) values (386, 'Golden Gate University');
insert into School (id, School) values (387, 'Tokushima University');
insert into School (id, School) values (388, 'Universidad Experimental Felix Adam');
insert into School (id, School) values (389, 'Shenkar School of Engineering & Design');
insert into School (id, School) values (390, 'Romanian-American University');
insert into School (id, School) values (391, 'Bates College');
insert into School (id, School) values (392, 'Sultan Haji Ahmad Shah Polytechnic');
insert into School (id, School) values (393, 'University of Piraeus');
insert into School (id, School) values (394, 'Kardan University');
insert into School (id, School) values (395, 'Universidad Iberoamericana');
insert into School (id, School) values (396, 'Centro Universitario de Occidente');
insert into School (id, School) values (397, 'African Virtual University');
insert into School (id, School) values (398, 'Kongju National University');
insert into School (id, School) values (399, 'Université Jean Monnet');
insert into School (id, School) values (400, 'Faculté Polytechnique de Mons');
insert into School (id, School) values (401, 'University of Nevada - Las Vegas');
insert into School (id, School) values (402, 'Latvian Maritime Academy');
insert into School (id, School) values (403, 'Pennsylvania State University - Berks-Lehigh Valley College');
insert into School (id, School) values (404, 'Instituto Superior Politécnico e Universitário');
insert into School (id, School) values (405, 'Université Chouaib Doukkali');
insert into School (id, School) values (406, 'Hankuk University of Foreign Studies');
insert into School (id, School) values (407, 'Washington Bible College');
insert into School (id, School) values (408, 'Pennsylvania State University - Schuylkill');
insert into School (id, School) values (409, 'Centre Universitaire de Technologie');
insert into School (id, School) values (410, 'University of Trento');
insert into School (id, School) values (411, 'Western Michigan University');
insert into School (id, School) values (412, 'University of Arkansas (System)');
insert into School (id, School) values (413, 'Westbrook University ');
insert into School (id, School) values (414, 'Aleksander Gieysztor School of Humanities in Pultusk');
insert into School (id, School) values (415, 'Al-Eman University');
insert into School (id, School) values (416, 'Technological University (Pakokku)');
insert into School (id, School) values (417, 'East Carolina University');
insert into School (id, School) values (418, 'American University of Afghanistan');
insert into School (id, School) values (419, 'Technological Education Institute of Patras');
insert into School (id, School) values (420, 'IASE (Institute of Advanced Studies) Deemed University');
insert into School (id, School) values (421, 'Instituto Superior de Saúde do Alto Ave');
insert into School (id, School) values (422, 'Universitas Lancang Kuning');
insert into School (id, School) values (423, 'Fachhochschule Merseburg');
insert into School (id, School) values (424, 'Universidad Laica "Vicente Rocafuerte" de Guayaquil');
insert into School (id, School) values (425, 'Idaho State University');
insert into School (id, School) values (426, 'University of International Business and Economics');
insert into School (id, School) values (427, 'Universidad Tecnologica "Vicente Perez Rosales"');
insert into School (id, School) values (428, 'Tumkur University');
insert into School (id, School) values (429, 'Ulyanovsk State University');
insert into School (id, School) values (430, 'Université Blaise Pascal (Clermont-Ferrand II)');
insert into School (id, School) values (431, 'Universiteit Doesburg (UNDO)');
insert into School (id, School) values (432, 'Capella University');
insert into School (id, School) values (433, 'San Francisco State University');
insert into School (id, School) values (434, 'Providence College');
insert into School (id, School) values (435, 'Technological Education Institute of Halkida, Euboea');
insert into School (id, School) values (436, 'Universidad Autónoma de Coahuila');
insert into School (id, School) values (437, 'Universidad Antonio Nariño');
insert into School (id, School) values (438, 'Ecole Nationale d''Ingénieurs de Saint-Etienne');
insert into School (id, School) values (439, 'Pillsbury Baptist Bible College');
insert into School (id, School) values (440, 'Aga Khan University');
insert into School (id, School) values (441, 'Southern Illinois University at Carbondale');
insert into School (id, School) values (442, 'Norwegian Teacher Academy for Studies in Religion and Education');
insert into School (id, School) values (443, 'Shanghai Lixin University of Commerce');
insert into School (id, School) values (444, 'Universidad España de Durango');
insert into School (id, School) values (445, 'Kiriri Womens University of Science and Technology');
insert into School (id, School) values (446, 'University of Otago');
insert into School (id, School) values (447, 'Persian Gulf University');
insert into School (id, School) values (448, 'Universität Hildesheim');
insert into School (id, School) values (449, 'ITT Technical Institute Maitland');
insert into School (id, School) values (450, 'St. Petersburg State University of Engineering and Economics');
insert into School (id, School) values (451, 'Korea Advanced Institute of Science & Technology');
insert into School (id, School) values (452, 'Northwestern University In Qatar');
insert into School (id, School) values (453, 'Acharya Nagarjuna University');
insert into School (id, School) values (454, 'Universidad del Norte');
insert into School (id, School) values (455, 'University of Puget Sound');
insert into School (id, School) values (456, 'Paichai University');
insert into School (id, School) values (457, 'Mount Aloysius College');
insert into School (id, School) values (458, 'Universidad de Las Palmas de Gran Canaria');
insert into School (id, School) values (459, 'Southern Methodist University');
insert into School (id, School) values (460, 'Integral University');
insert into School (id, School) values (461, 'Université d''Alger');
insert into School (id, School) values (462, 'Stillman College');
insert into School (id, School) values (463, 'Tierärztliche Hochschule Hannover');
insert into School (id, School) values (464, 'University of Technology - Iraq');
insert into School (id, School) values (465, 'Buraydah College for Applied Medical Sciences');
insert into School (id, School) values (466, 'Kampala University');
insert into School (id, School) values (467, 'Tohoku University');
insert into School (id, School) values (468, 'African Virtual University');
insert into School (id, School) values (469, 'University of Calabar');
insert into School (id, School) values (470, 'St. Thomas Aquinas College');
insert into School (id, School) values (471, 'Dalian Medical University');
insert into School (id, School) values (472, 'Universidad Distral "Francisco José de Caldas"');
insert into School (id, School) values (473, 'Bucknell University');
insert into School (id, School) values (474, 'Khulna University');
insert into School (id, School) values (475, 'University of Central Europe in Skalica');
insert into School (id, School) values (476, 'Tashkent Pharmaceutical Institute');
insert into School (id, School) values (477, 'Universidad Autónoma de Sinaloa');
insert into School (id, School) values (478, 'Université Claude Bernard (Lyon I)');
insert into School (id, School) values (479, 'China Medical College');
insert into School (id, School) values (480, 'University of North Carolina at Pembroke');
insert into School (id, School) values (481, 'University of Wisconsin - Superior');
insert into School (id, School) values (482, 'Lehigh Univervsity');
insert into School (id, School) values (483, 'Shahrekord University');
insert into School (id, School) values (484, 'Eastern Virginia Medical School');
insert into School (id, School) values (485, 'University of Alaska - Southeast');
insert into School (id, School) values (486, 'Miyagi University of Education');
insert into School (id, School) values (487, 'University of New Haven');
insert into School (id, School) values (488, 'Qassim University');
insert into School (id, School) values (489, 'Bodo Regional University');
insert into School (id, School) values (490, 'Universidad Santo Tomás');
insert into School (id, School) values (491, 'Deutsche Hochschule für Verwaltungswissenschaften Speyer');
insert into School (id, School) values (492, 'Aomori Chuoh Gakuin University');
insert into School (id, School) values (493, 'Cologne Business School');
insert into School (id, School) values (494, 'Bucknell University');
insert into School (id, School) values (495, 'Kyungsung University');
insert into School (id, School) values (496, 'Emerson College');
insert into School (id, School) values (497, 'Kharkiv National University of Radio Electronics');
insert into School (id, School) values (498, 'The Illinois Institute of Art-Chicago');
insert into School (id, School) values (499, 'Universidad Francisco de Aguirre');
insert into School (id, School) values (500, 'Kodolanyi Janos University College');
insert into School (id, School) values (501, 'Godfrey Okoye University ');
insert into School (id, School) values (502, 'Ecole Nationale Supérieure en Electrotechnique, Electronique, Informatique et Hydraulique de Toulouse');
insert into School (id, School) values (503, 'University of Da Nang');
insert into School (id, School) values (504, 'University of Education');
insert into School (id, School) values (505, 'Universidad Privada del Valle');
insert into School (id, School) values (506, 'University of Wisconsin - Superior');
insert into School (id, School) values (507, 'University of Liberal Arts');
insert into School (id, School) values (508, 'Gratz College');
insert into School (id, School) values (509, 'Campus Bio-Medico University of Rome');
insert into School (id, School) values (510, 'Universidade Eduardo Mondlane');
insert into School (id, School) values (511, 'Universidad Católica de Santiago de Guayaquil');
insert into School (id, School) values (512, 'Fine Arts Academy Wladyslaw Strzeminski in Lodz');
insert into School (id, School) values (513, 'Kyunghee University');
insert into School (id, School) values (514, 'Rajasthan Vidyapeeth University');
insert into School (id, School) values (515, 'Universidade Camilo Castelo Branco');
insert into School (id, School) values (516, 'Universitas Muslim Indonesia');
insert into School (id, School) values (517, 'Bentley College');
insert into School (id, School) values (518, 'Universitas Janabadra');
insert into School (id, School) values (519, 'Universidad Privada Boliviana');
insert into School (id, School) values (520, 'Rush University');
insert into School (id, School) values (521, 'Yildiz Technical University');
insert into School (id, School) values (522, 'Immaculata University');
insert into School (id, School) values (523, 'Kobe Shoin Women''s University');
insert into School (id, School) values (524, 'University of Stellenbosch');
insert into School (id, School) values (525, 'Instituto Superior Bissaya Barreto');
insert into School (id, School) values (526, 'University of Agriculture and Veterinary Medicine Cluj-Napoca');
insert into School (id, School) values (527, 'Universidad La Republica');
insert into School (id, School) values (528, 'State Engineering University of Armenia');
insert into School (id, School) values (529, 'Universidad Nacional de Ingeniería');
insert into School (id, School) values (530, 'Huntington College');
insert into School (id, School) values (531, 'Catholic University of Malawi');
insert into School (id, School) values (532, 'National Sun Yat-Sen University');
insert into School (id, School) values (533, 'University of Catania');
insert into School (id, School) values (534, 'Université Paris Sud (Paris XI)');
insert into School (id, School) values (535, 'Nazarene Bible College');
insert into School (id, School) values (536, 'Tabor College');
insert into School (id, School) values (537, 'Avondale College');
insert into School (id, School) values (538, 'College of Busniess Admnistration');
insert into School (id, School) values (539, 'University of Liverpool');
insert into School (id, School) values (540, 'University of Health Sciences');
insert into School (id, School) values (541, 'Al-Zaytoonah University');
insert into School (id, School) values (542, 'Gustav-Siewerth-Akademie');
insert into School (id, School) values (543, 'Tennessee Wesleyan College');
insert into School (id, School) values (544, 'Babes-Bolyai University of Cluj-Napoca');
insert into School (id, School) values (545, 'University of Northumbria at Newcastle');
insert into School (id, School) values (546, 'Universidade Aberta Lisboa');
insert into School (id, School) values (547, 'University of Bucharest');
insert into School (id, School) values (548, 'VBS Purvanchal University');
insert into School (id, School) values (549, 'University of Central Florida');
insert into School (id, School) values (550, 'Murray State University');
insert into School (id, School) values (551, 'Universidad Peruana de Ciencias Aplicadas');
insert into School (id, School) values (552, 'Aleksander Gieysztor School of Humanities in Pultusk');
insert into School (id, School) values (553, 'Detroit College of Law');
insert into School (id, School) values (554, 'Institute of Business Management ');
insert into School (id, School) values (555, 'Universiteit Doesburg (UNDO)');
insert into School (id, School) values (556, 'Kwantleen University College');
insert into School (id, School) values (557, 'Ecole Nationale Supérieure d''Ingénieurs de Génie Chimique');
insert into School (id, School) values (558, 'University of Applied Sciences Rapperswil');
insert into School (id, School) values (559, 'Marietta College');
insert into School (id, School) values (560, 'Hungarian Academy of Fine Arts Budapest');
insert into School (id, School) values (561, 'Chongqing Wenli University');
insert into School (id, School) values (562, 'Brussels Management School (ICHEC)');
insert into School (id, School) values (563, 'Augustana University College');
insert into School (id, School) values (564, 'Concordia University, Austin');
insert into School (id, School) values (565, 'Universitas Widyatama');
insert into School (id, School) values (566, 'Jalalabad State University Kyrgyzstan');
insert into School (id, School) values (567, 'Universidad Autonoma del Sur');
insert into School (id, School) values (568, 'Walla Walla College');
insert into School (id, School) values (569, 'Nizhny Novgorod State Academy of Medicine');
insert into School (id, School) values (570, 'Tampere Polytechnic');
insert into School (id, School) values (571, 'University of Portland');
insert into School (id, School) values (572, 'Mahidol University International College');
insert into School (id, School) values (573, 'National Chung Cheng University');
insert into School (id, School) values (574, 'Inner Mongolia Agricultural University');
insert into School (id, School) values (575, 'Umea University');
insert into School (id, School) values (576, 'Indiana University at South Bend');
insert into School (id, School) values (577, 'University of Split');
insert into School (id, School) values (578, 'Frostburg State University');
insert into School (id, School) values (579, 'Dalian University');
insert into School (id, School) values (580, 'Nivadhana University');
insert into School (id, School) values (581, 'Technical University of Bialystok');
insert into School (id, School) values (582, 'Universitas Bojonegoro');
insert into School (id, School) values (583, 'Ecole Nationale d''Ingénieurs de Tarbes');
insert into School (id, School) values (584, 'Drake University');
insert into School (id, School) values (585, 'Adekunle Ajasin University');
insert into School (id, School) values (586, 'Shahid Bahonar University of Kerman');
insert into School (id, School) values (587, 'Voronezh State Technical University');
insert into School (id, School) values (588, 'University of Charleston');
insert into School (id, School) values (589, 'George Brown College');
insert into School (id, School) values (590, 'Universidad Católica Santo Toribio de Mogrovejo');
insert into School (id, School) values (591, 'Ecole des Hautes Etudes Commerciales MAROC');
insert into School (id, School) values (592, 'University of the South Pacific School of Agriculture');
insert into School (id, School) values (593, 'Business and Hotel Management School');
insert into School (id, School) values (594, 'Fachhochschule Ravensburg-Weingarten');
insert into School (id, School) values (595, 'University of San Jose Recoletos');
insert into School (id, School) values (596, 'College of Science, Baghdad University');
insert into School (id, School) values (597, 'Universiti Teknikal Malaysia Melaka');
insert into School (id, School) values (598, 'University of South Carolina - Beaufort');
insert into School (id, School) values (599, 'Ecole Nationale Supérieure Agronomique de Toulouse');
insert into School (id, School) values (600, 'Saad College of Nursing and Allied Health Sciences');
insert into School (id, School) values (601, 'Universidad Autónoma de Tlaxcala');
insert into School (id, School) values (602, 'University of Art and Design Cluj-Napoca');
insert into School (id, School) values (603, 'Université Quisqueya');
insert into School (id, School) values (604, 'Ecole Nationale Supérieur d''Ingénieurs de Constructions Aéronautique');
insert into School (id, School) values (605, 'Universidad NUR');
insert into School (id, School) values (606, 'Georgian Court College');
insert into School (id, School) values (607, 'University of Trnava');
insert into School (id, School) values (608, 'Free International University of Social Studies');
insert into School (id, School) values (609, 'William Mitchell College of Law');
insert into School (id, School) values (610, 'University of Guam');
insert into School (id, School) values (611, 'Cabrini College');
insert into School (id, School) values (612, 'Lucerne University of Applied Sciences and Arts ');
insert into School (id, School) values (613, 'Taipei Medical College');
insert into School (id, School) values (614, 'Universidad Autónoma de Guerrero');
insert into School (id, School) values (615, 'Standford Online University');
insert into School (id, School) values (616, 'University College of Cape Breton');
insert into School (id, School) values (617, 'Technische Fachhochschule Berlin');
insert into School (id, School) values (618, 'Ecole Nationale Supérieure de Techniques Avancées');
insert into School (id, School) values (619, 'Universität für Musik und darstellende Kunst  Wien');
insert into School (id, School) values (620, 'Notre Dame College of Ohio');
insert into School (id, School) values (621, 'Ternopil State Ivan Pul''uj Technical University');
insert into School (id, School) values (622, 'Karaganda State Technical University');
insert into School (id, School) values (623, 'Busitema University');
insert into School (id, School) values (624, 'Wells College');
insert into School (id, School) values (625, 'Osmangazi University');
insert into School (id, School) values (626, 'Mendeleev Russian University of Chemical Technology');
insert into School (id, School) values (627, 'Biju Pattnaik University of Technology');
insert into School (id, School) values (628, 'St. Mary-of-the-Woods College');
insert into School (id, School) values (629, 'Ecole Supérieure de Commerce de Brest');
insert into School (id, School) values (630, 'Istanbul Technical University');
insert into School (id, School) values (631, 'Universidad Nacional de Ingeniería');
insert into School (id, School) values (632, 'Kashan University');
insert into School (id, School) values (633, 'National Pedagogical University M. Dragomanov ');
insert into School (id, School) values (634, 'Université de Guelma');
insert into School (id, School) values (635, 'Trinity University School of Medicine');
insert into School (id, School) values (636, 'Open University of Tanzania');
insert into School (id, School) values (637, 'University of Central Arkansas');
insert into School (id, School) values (638, 'Veritas University');
insert into School (id, School) values (639, 'Institut des Sciences de la Matière et du Rayonnement');
insert into School (id, School) values (640, 'National Academy for Theatre and Film Arts "Krustju Sarafov"');
insert into School (id, School) values (641, 'Universidad de San Buenaventura Medellin');
insert into School (id, School) values (642, 'University of Arkansas at Pine Bluff');
insert into School (id, School) values (643, 'Toyama University of International Studies');
insert into School (id, School) values (644, 'Omsk State Agrarian University');
insert into School (id, School) values (645, 'Ecole Nationale Supérieure de Physique de Grenoble');
insert into School (id, School) values (646, 'University of Wollongong');
insert into School (id, School) values (647, 'Tokiwa University');
insert into School (id, School) values (648, 'Universidad Peruana Union');
insert into School (id, School) values (649, 'National Taipei University of Technology');
insert into School (id, School) values (650, 'University of Prince Edward Island');
insert into School (id, School) values (651, 'Kyoto Prefectural University');
insert into School (id, School) values (652, 'Agricultural University of Tirane');
insert into School (id, School) values (653, 'Pamukkale University');
insert into School (id, School) values (654, 'Altai State Technical University');
insert into School (id, School) values (655, 'Ch. Charan Singh University');
insert into School (id, School) values (656, 'Universitas Muhammadiyah Surakarta');
insert into School (id, School) values (657, 'Multimedia University');
insert into School (id, School) values (658, 'Nihon University');
insert into School (id, School) values (659, 'Al-Wataniya Private University');
insert into School (id, School) values (660, 'Ashiya University');
insert into School (id, School) values (661, 'Eastern University of Sri Lanka');
insert into School (id, School) values (662, 'Minsk State Linguistic University');
insert into School (id, School) values (663, 'West Virginia State College');
insert into School (id, School) values (664, 'Music Academy "Felix Nowowiejski" in Bydgoszcz');
insert into School (id, School) values (665, 'Wofford College');
insert into School (id, School) values (666, 'Northwest University');
insert into School (id, School) values (667, 'Hemwati Nandan Bahuguna Garhwal University');
insert into School (id, School) values (668, 'Breyer State University (Virtual University)');
insert into School (id, School) values (669, 'University of North Carolina at Chapel Hill');
insert into School (id, School) values (670, 'University of Lahore');
insert into School (id, School) values (671, 'Universidade do Oeste Paulista');
insert into School (id, School) values (672, 'Araullo University');
insert into School (id, School) values (673, 'Bauman Moscow State Technical University');
insert into School (id, School) values (674, 'Daffodil International University');
insert into School (id, School) values (675, 'University of Colorado at Denver');
insert into School (id, School) values (676, 'University of Petroleum (East China)');
insert into School (id, School) values (677, 'International Business University of Beijing');
insert into School (id, School) values (678, 'Universidad Tecnológica Centroamericana');
insert into School (id, School) values (679, 'St. John''s College Maryland');
insert into School (id, School) values (680, 'Moore College of Art and Design');
insert into School (id, School) values (681, 'Cleveland State University');
insert into School (id, School) values (682, 'Kurashiki Sakuyo University');
insert into School (id, School) values (683, 'Instituto Nacional de Matemática Pura e Aplicada - IMPA');
insert into School (id, School) values (684, 'Shanghai University of Engineering Science');
insert into School (id, School) values (685, 'The Global College Lahore');
insert into School (id, School) values (686, 'Theologische Hochschule Friedensau');
insert into School (id, School) values (687, 'Nortre Dame Seishin University');
insert into School (id, School) values (688, 'Universidade do Porto');
insert into School (id, School) values (689, 'National College of Chiropractic');
insert into School (id, School) values (690, 'Siberian State University of Telecommunications and Informatics');
insert into School (id, School) values (691, 'California State University, Chico');
insert into School (id, School) values (692, 'Black Hills State University');
insert into School (id, School) values (693, 'Universidad de Sevilla');
insert into School (id, School) values (694, 'Tianjin Normal University');
insert into School (id, School) values (695, 'University of Moncton, Shippagan');
insert into School (id, School) values (696, 'Mustafa Kemal University');
insert into School (id, School) values (697, 'Universidad Católica de Manizales');
insert into School (id, School) values (698, 'Indian Institute of Technology, Roorkee');
insert into School (id, School) values (699, 'Odessa State Academy of Construction and Architecture');
insert into School (id, School) values (700, 'University of Andorra');
insert into School (id, School) values (701, 'University of the Arts');
insert into School (id, School) values (702, 'Canisius College');
insert into School (id, School) values (703, 'Fachhochschule Nordhessen');
insert into School (id, School) values (704, 'University of Finance and Management in Bialystok');
insert into School (id, School) values (705, 'I.M. Sechenov Moscow Medical Academy');
insert into School (id, School) values (706, 'Kisii University');
insert into School (id, School) values (707, 'Makerere University');
insert into School (id, School) values (708, 'COMSATS Institute of Information Technology, Lahore');
insert into School (id, School) values (709, 'Tohoku University');
insert into School (id, School) values (710, 'Osaka City University');
insert into School (id, School) values (711, 'Henan Normal University');
insert into School (id, School) values (712, 'Augsburg College');
insert into School (id, School) values (713, 'Omdurman Ahlia University');
insert into School (id, School) values (714, 'Iranian Academy of Persian Language and Literature');
insert into School (id, School) values (715, 'Le Moyne-Owen College');
insert into School (id, School) values (716, 'Dongguk University');
insert into School (id, School) values (717, 'The Federal Polytechnic Offa');
insert into School (id, School) values (718, 'Westmont College');
insert into School (id, School) values (719, 'University of Minnesota - Crookston');
insert into School (id, School) values (720, 'Dordt College');
insert into School (id, School) values (721, 'Blackburn College');
insert into School (id, School) values (722, ' Technological University (Yangon)');
insert into School (id, School) values (723, 'Marmara University');
insert into School (id, School) values (724, 'College of Education Ikere');
insert into School (id, School) values (725, 'İstanbul Şehir University');
insert into School (id, School) values (726, 'Instituto Nacional de Educación Física "General Manuel Belgrano"');
insert into School (id, School) values (727, 'New York Law School');
insert into School (id, School) values (728, 'Universidad del Pacifico');
insert into School (id, School) values (729, 'Debre Birhan University');
insert into School (id, School) values (730, 'Theologische Fakultät Paderborn');
insert into School (id, School) values (731, 'University of Tampere');
insert into School (id, School) values (732, 'Angkor University');
insert into School (id, School) values (733, 'Universidad Franciscana de México');
insert into School (id, School) values (734, 'Université du Québec à Montréal');
insert into School (id, School) values (735, 'Notre Dame University');
insert into School (id, School) values (736, 'Shandong Medical University');
insert into School (id, School) values (737, 'Staszic Pila College');
insert into School (id, School) values (738, 'University of Southern Philippines Foundation');
insert into School (id, School) values (739, 'Chiba Keizai University');
insert into School (id, School) values (740, 'Hemchandracharay North Gujarat University');
insert into School (id, School) values (741, 'Komazawa University');
insert into School (id, School) values (742, 'Kar University');
insert into School (id, School) values (743, 'Hyogo College of Medicine');
insert into School (id, School) values (744, 'Etisalat University College');
insert into School (id, School) values (745, 'Najaf Abad University of Applied Science and Technology');
insert into School (id, School) values (746, 'University of the Thai Chamber of Commerce');
insert into School (id, School) values (747, 'Tehran University of Teacher Training');
insert into School (id, School) values (748, 'Academy of Economics "Dimitur A. Tscenov"');
insert into School (id, School) values (749, 'Thomas A. Edison State College');
insert into School (id, School) values (750, 'Odessa National Academy of Food Technologies');
insert into School (id, School) values (751, 'West Coast University');
insert into School (id, School) values (752, 'University of Northern British Columbia');
insert into School (id, School) values (753, 'Northwood University, Texas Campus');
insert into School (id, School) values (754, 'Academy of Fine Arts');
insert into School (id, School) values (755, 'Menlo College');
insert into School (id, School) values (756, 'Instituto Superior de Assistentes e Intérpretes');
insert into School (id, School) values (757, 'Universidade de Brasília');
insert into School (id, School) values (758, 'Nanjing Institute of Meteorology');
insert into School (id, School) values (759, 'Hebei Academy of Fine Art');
insert into School (id, School) values (760, 'Lewis and Clark College');
insert into School (id, School) values (761, 'Tver State Technical University');
insert into School (id, School) values (762, 'Universidad Nacional de la Patagonia "San Juan Bosco"');
insert into School (id, School) values (763, 'Lagos City Polytechnic');
insert into School (id, School) values (764, 'Universidad de la Empresa (UDE)');
insert into School (id, School) values (765, 'Alma College');
insert into School (id, School) values (766, 'Hanoi University of Mining and Geology');
insert into School (id, School) values (767, 'Universidad Nuestra Senora de La Paz');
insert into School (id, School) values (768, 'Universidade Tiradentes');
insert into School (id, School) values (769, 'University of Bialystok');
insert into School (id, School) values (770, 'Kharkiv National University');
insert into School (id, School) values (771, 'Japan Advanced Institute of Science and Technology');
insert into School (id, School) values (772, 'Midway College');
insert into School (id, School) values (773, 'Universidad Academia de Humanismo Cristiano');
insert into School (id, School) values (774, 'State University of New York Downstate Medical Center');
insert into School (id, School) values (775, 'Eötvös Lorand University');
insert into School (id, School) values (776, 'Kyushu Dental College');
insert into School (id, School) values (777, 'Benson Idahosa University');
insert into School (id, School) values (778, 'University of Mauritius');
insert into School (id, School) values (779, 'Canisius College');
insert into School (id, School) values (780, 'Lourdes College');
insert into School (id, School) values (781, 'Technische Universität Wien');
insert into School (id, School) values (782, 'Caucasus University');
insert into School (id, School) values (783, 'Institute of Management Development - Ohrid');
insert into School (id, School) values (784, 'American University of Afghanistan');
insert into School (id, School) values (785, 'Norwegian University of Science and Technology');
insert into School (id, School) values (786, 'I.M. Sechenov Moscow Medical Academy');
insert into School (id, School) values (787, 'University of the Southwest');
insert into School (id, School) values (788, 'Universidad de La Guajira');
insert into School (id, School) values (789, 'Universitat Oberta de Catalunya');
insert into School (id, School) values (790, 'Batchelor Institute of Indigenous Tertiary Education');
insert into School (id, School) values (791, 'Abai State University');
insert into School (id, School) values (792, 'Ecole Nationale d''Ingénieurs de Metz');
insert into School (id, School) values (793, 'State University of New York College of Technology at Farmingdale');
insert into School (id, School) values (794, 'Islamic Azad University, Bostanabad');
insert into School (id, School) values (795, 'St. Louis University');
insert into School (id, School) values (796, 'Griffith University');
insert into School (id, School) values (797, 'Altai State Technical University');
insert into School (id, School) values (798, 'Jawaharlal Nehru University');
insert into School (id, School) values (799, 'Escola Superior de Artes e Design');
insert into School (id, School) values (800, 'Beth-El College of Nursing and Health Sciences');
insert into School (id, School) values (801, 'Al-Quds Open University');
insert into School (id, School) values (802, 'Universidad de Puerto Rico, Aguadilla');
insert into School (id, School) values (803, 'Universidad Privada del Este');
insert into School (id, School) values (804, 'Universidad Pedagógica de El Salvador');
insert into School (id, School) values (805, 'Rajendra Agricultural University');
insert into School (id, School) values (806, 'University of the Assumption');
insert into School (id, School) values (807, 'Louisiana State University Health Sciences Center New Orleans');
insert into School (id, School) values (808, 'University of Montana');
insert into School (id, School) values (809, 'Kunmimg University of Science and Technology');
insert into School (id, School) values (810, 'Northern Institute of Technology Management (NIT)');
insert into School (id, School) values (811, 'University of Sudbury');
insert into School (id, School) values (812, 'American University Extension, Okinawa');
insert into School (id, School) values (813, 'Norway''s Information Technology University College');
insert into School (id, School) values (814, 'American University in Cairo');
insert into School (id, School) values (815, 'Birzeit University');
insert into School (id, School) values (816, 'University of Divinity');
insert into School (id, School) values (817, 'Texas Wesleyan University');
insert into School (id, School) values (818, 'Wolaita Sodo University');
insert into School (id, School) values (819, 'Université de Pau et des Pays de l''Adour');
insert into School (id, School) values (820, 'Northwestern College St. Paul');
insert into School (id, School) values (821, 'Universidade Metropolitana de Angola');
insert into School (id, School) values (822, 'Volgograd Medical Academy');
insert into School (id, School) values (823, 'Southern Cross University');
insert into School (id, School) values (824, 'Faulkner University');
insert into School (id, School) values (825, 'Molloy College');
insert into School (id, School) values (826, 'Technion - Israel Institute of Technology');
insert into School (id, School) values (827, 'Columbia College Chicago');
insert into School (id, School) values (828, 'Belmont Abbey College');
insert into School (id, School) values (829, 'Universidad del Noroeste');
insert into School (id, School) values (830, 'Campion College');
insert into School (id, School) values (831, 'SMK Fomra Institute of Technology');
insert into School (id, School) values (832, 'University Institute of Modern Languages');
insert into School (id, School) values (833, 'Universidade de Taubaté');
insert into School (id, School) values (834, 'Indian Law Institue');
insert into School (id, School) values (835, 'Universidad Lasallista Benavente');
insert into School (id, School) values (836, 'Doshisha Women''s College of Liberal Arts');
insert into School (id, School) values (837, 'Arab American University - Jenin');
insert into School (id, School) values (838, 'Allianze College of Medical Sciences (ACMS)');
insert into School (id, School) values (839, 'Manuel S. Enverga University Foundation');
insert into School (id, School) values (840, 'Japanese Red Cross College of Nursing');
insert into School (id, School) values (841, 'Universidad Tecnológica Oteima');
insert into School (id, School) values (842, 'Fachhochschule Furtwangen, Hochschule für Technik und Wirtschaft');
insert into School (id, School) values (843, 'Prague International University');
insert into School (id, School) values (844, 'Wilmington College');
insert into School (id, School) values (845, 'Mercy College');
insert into School (id, School) values (846, 'Université d''Alger 3');
insert into School (id, School) values (847, 'Institute of Teachers Education, Sarawak');
insert into School (id, School) values (848, 'University of Management and Technology ');
insert into School (id, School) values (849, 'Campbell University');
insert into School (id, School) values (850, 'Université Dakar Bourguiba');
insert into School (id, School) values (851, 'University of Verona');
insert into School (id, School) values (852, 'Silliman University');
insert into School (id, School) values (853, 'Tilburg University');
insert into School (id, School) values (854, 'School of Management');
insert into School (id, School) values (855, 'University of Nevada - Las Vegas');
insert into School (id, School) values (856, 'National Taras Shevchenko University of Kiev');
insert into School (id, School) values (857, 'Makhanlal Chaturvedi National University of Journalism and Communication');
insert into School (id, School) values (858, 'Islamic Azad University, Aliabad ');
insert into School (id, School) values (859, 'Lithunian Academy of Music and Theatre');
insert into School (id, School) values (860, 'Keene State College');
insert into School (id, School) values (861, 'Technische Universität München');
insert into School (id, School) values (862, 'Universidad de Extremadura');
insert into School (id, School) values (863, 'Moscow P. I. Tchaikovsky Conservatory');
insert into School (id, School) values (864, 'Kingston University');
insert into School (id, School) values (865, 'University of Seychelles - American Institute of Medicine');
insert into School (id, School) values (866, 'Southwestern Christian College');
insert into School (id, School) values (867, 'College of Notre Dame');
insert into School (id, School) values (868, 'University of Peradeniya');
insert into School (id, School) values (869, 'Gemsville Technical University');
insert into School (id, School) values (870, 'Anna University of Technology, Tirunelveli');
insert into School (id, School) values (871, 'Lagos City Polytechnic');
insert into School (id, School) values (872, 'University of the East, Manila');
insert into School (id, School) values (873, 'Tomsk State University');
insert into School (id, School) values (874, 'Universidad de las Américas');
insert into School (id, School) values (875, 'Le Moyne-Owen College');
insert into School (id, School) values (876, 'European University');
insert into School (id, School) values (877, 'Cyprus International University');
insert into School (id, School) values (878, 'Jewish University in Moscow');
insert into School (id, School) values (879, 'Universidad de Caldas');
insert into School (id, School) values (880, 'Ionian University Corfu');
insert into School (id, School) values (881, 'Universidade Católica de Goiás');
insert into School (id, School) values (882, 'Nihon University');
insert into School (id, School) values (883, 'Universidad de Colima');
insert into School (id, School) values (884, 'University of Luxemburg');
insert into School (id, School) values (885, 'Moscow Institute of Physics and Technology');
insert into School (id, School) values (886, 'Palacky University');
insert into School (id, School) values (887, 'Oduduwa University');
insert into School (id, School) values (888, 'Bellin College of Nursing');
insert into School (id, School) values (889, 'Manipal University');
insert into School (id, School) values (890, 'Busitema University');
insert into School (id, School) values (891, 'Tusculum College');
insert into School (id, School) values (892, 'Capella University');
insert into School (id, School) values (893, 'Wofford College');
insert into School (id, School) values (894, 'Banaras Hindu University');
insert into School (id, School) values (895, 'Guangxi Medical University');
insert into School (id, School) values (896, 'Brunswick Community College');
insert into School (id, School) values (897, 'Universidad de San Andres');
insert into School (id, School) values (898, 'Institute of Finance');
insert into School (id, School) values (899, 'Southwestern University');
insert into School (id, School) values (900, 'Nankai University');
insert into School (id, School) values (901, 'Ferris University');
insert into School (id, School) values (902, 'Universidad de la Cuenca del Plata');
insert into School (id, School) values (903, 'Charter Oak State College');
insert into School (id, School) values (904, 'Banat''s University of Agricultural Sciences');
insert into School (id, School) values (905, 'Konan Women''s University');
insert into School (id, School) values (906, 'St. Petersburg State Conservatory');
insert into School (id, School) values (907, 'Universidade Estadual do Maranhão');
insert into School (id, School) values (908, 'Centre Universitaire de Tiaret');
insert into School (id, School) values (909, 'International Higher School for Advanced Studies Trieste');
insert into School (id, School) values (910, 'Wheelock College');
insert into School (id, School) values (911, 'Brewton-Parker College');
insert into School (id, School) values (912, 'University of Lapland');
insert into School (id, School) values (913, 'Qauid-e-Awam University of Engineering Sciences & Technology');
insert into School (id, School) values (914, 'B.P.Koirala Institute of Health Sciences');
insert into School (id, School) values (915, 'Sudan Academy of Sciences');
insert into School (id, School) values (916, 'Hungarian University of Physical Education');
insert into School (id, School) values (917, 'Universidad Autónoma de la Ciudad de México');
insert into School (id, School) values (918, 'Siena College');
insert into School (id, School) values (919, 'Universidad Técnica "Federico Santa María"');
insert into School (id, School) values (920, 'Université du Québec en Outaouais');
insert into School (id, School) values (921, 'Elrazi College Of Medical & Technological Sciences');
insert into School (id, School) values (922, 'Hanoi Medical University');
insert into School (id, School) values (923, 'Capital University Law School');
insert into School (id, School) values (924, 'Catholic University of the Sacred Heart');
insert into School (id, School) values (925, 'Universidade Estadual do Oeste do Paraná');
insert into School (id, School) values (926, 'University of Sibiu');
insert into School (id, School) values (927, 'Nippon Dental University');
insert into School (id, School) values (928, 'University of Pune');
insert into School (id, School) values (929, 'Universidad José Santos Ossa');
insert into School (id, School) values (930, 'Hvanneyri Agricultural University');
insert into School (id, School) values (931, 'Birsk State Pedagogical Institute');
insert into School (id, School) values (932, 'Towson University');
insert into School (id, School) values (933, 'Kazan State University');
insert into School (id, School) values (934, 'University of Nigeria');
insert into School (id, School) values (935, 'University of Medicine and Pharmacy of Cluj-Napoca');
insert into School (id, School) values (936, 'Universidade de Brasília');
insert into School (id, School) values (937, 'Athens Laboratory of Business Administration (ALBA)');
insert into School (id, School) values (938, 'Babol University of Medical Sciences');
insert into School (id, School) values (939, 'Shah Abdul Latif University Khairpur');
insert into School (id, School) values (940, 'Harvey Mudd College');
insert into School (id, School) values (941, 'Morehouse College');
insert into School (id, School) values (942, 'West Minster International College');
insert into School (id, School) values (943, 'Leading University');
insert into School (id, School) values (944, 'Bentley College');
insert into School (id, School) values (945, 'University of California, Santa Cruz');
insert into School (id, School) values (946, 'Columbus College of Art and Design');
insert into School (id, School) values (947, 'Universidad de Aconcagua');
insert into School (id, School) values (948, 'Hogeschool West-Vlaanderen (TU)');
insert into School (id, School) values (949, 'Davis and Elkins College');
insert into School (id, School) values (950, 'Coleman College');
insert into School (id, School) values (951, 'International University of Kagoshima');
insert into School (id, School) values (952, 'Graduate School of Business Administration Zurich (GSBA Zurich)');
insert into School (id, School) values (953, 'University of Management and Technology');
insert into School (id, School) values (954, 'Olabisi Onabanjo University ');
insert into School (id, School) values (955, 'Universidad Modular Abierta');
insert into School (id, School) values (956, 'Daito Bunka University');
insert into School (id, School) values (957, 'Université de Bandundu Ville');
insert into School (id, School) values (958, 'Faisalabad Institute of Textile and Fashion Design');
insert into School (id, School) values (959, 'Martin-Luther Universität Halle-Wittenberg');
insert into School (id, School) values (960, 'Crescent University');
insert into School (id, School) values (961, 'Mae Fah Luang University ');
insert into School (id, School) values (962, 'University of Massachusetts at Dartmouth');
insert into School (id, School) values (963, 'Universidad Nacional de Rosario');
insert into School (id, School) values (964, 'Brewton-Parker College');
insert into School (id, School) values (965, 'Birsk State Pedagogical Institute');
insert into School (id, School) values (966, 'Kansai Medical University');
insert into School (id, School) values (967, 'Vermont Technical College');
insert into School (id, School) values (968, 'Carroll College Waukesha');
insert into School (id, School) values (969, 'Universitas Negeri Makassar');
insert into School (id, School) values (970, 'Fachhochschule Koblenz');
insert into School (id, School) values (971, 'Tokyo Denki University');
insert into School (id, School) values (972, 'Islamic Azad University, Majlesi');
insert into School (id, School) values (973, 'State University of New York College at Brockport');
insert into School (id, School) values (974, 'Latvian Maritime Academy');
insert into School (id, School) values (975, 'Hankyong National University');
insert into School (id, School) values (976, 'Silpakorn University');
insert into School (id, School) values (977, 'St. Matthews University');
insert into School (id, School) values (978, 'Ural Gorkij State University');
insert into School (id, School) values (979, 'Universidad de Flores - Buenos Aires');
insert into School (id, School) values (980, 'Universidad Cooperativa de Colombia');
insert into School (id, School) values (981, 'Bengal Engineering College');
insert into School (id, School) values (982, 'Kameshwar Singh Darbhanga Sanskrit University');
insert into School (id, School) values (983, 'National American University, Roseville');
insert into School (id, School) values (984, 'East Somalia University');
insert into School (id, School) values (985, 'Aristotle University of Thessaloniki');
insert into School (id, School) values (986, 'Business & Computer University College');
insert into School (id, School) values (987, 'Mzuzu University');
insert into School (id, School) values (988, 'University of Hertfordshire');
insert into School (id, School) values (989, 'Universidad José Santos Ossa');
insert into School (id, School) values (990, 'Technische Universität Clausthal');
insert into School (id, School) values (991, 'Pfeiffer University');
insert into School (id, School) values (992, 'Damanhour University');
insert into School (id, School) values (993, 'Aichi Prefectural University of Fine Arts & Music');
insert into School (id, School) values (994, 'Fachhochschule Ingolstadt');
insert into School (id, School) values (995, 'Northern Michigan University');
insert into School (id, School) values (996, 'Norwich University');
insert into School (id, School) values (997, 'Selcuk University');
insert into School (id, School) values (998, 'Instituto Superior de Ciências Empresariais e de Turismo');
insert into School (id, School) values (999, 'Tianjin Academy of Fine Art');
insert into School (id, School) values (1000, 'Instituto Superior Politécnico José Antonio Echeverría');
