create table City (
	id INT,
	City VARCHAR(50)
);
insert into City (id, City) values (1, 'Jingchuan Chengguanzhen');
insert into City (id, City) values (2, 'Tirmiz');
insert into City (id, City) values (3, 'Tafí del Valle');
insert into City (id, City) values (4, 'Lizhuang');
insert into City (id, City) values (5, 'Karlstad');
insert into City (id, City) values (6, 'Ganshui');
insert into City (id, City) values (7, 'Österbybruk');
insert into City (id, City) values (8, 'Kutorejo');
insert into City (id, City) values (9, 'Bahía Blanca');
insert into City (id, City) values (10, 'Североморск-3');
insert into City (id, City) values (11, 'Putrajaya');
insert into City (id, City) values (12, 'Cikendi');
insert into City (id, City) values (13, 'Bāmyān');
insert into City (id, City) values (14, 'Nangger');
insert into City (id, City) values (15, 'Ciénaga de Oro');
insert into City (id, City) values (16, 'Dziergowice');
insert into City (id, City) values (17, 'Wichit');
insert into City (id, City) values (18, 'Shangyong');
insert into City (id, City) values (19, 'Pontes e Lacerda');
insert into City (id, City) values (20, 'Rozsypne');
insert into City (id, City) values (21, 'Rumphi');
insert into City (id, City) values (22, 'Brandýs nad Labem-Stará Boleslav');
insert into City (id, City) values (23, 'Malanje');
insert into City (id, City) values (24, 'Shiroishi');
insert into City (id, City) values (25, 'Phan Thong');
insert into City (id, City) values (26, 'An Naşşārīyah');
insert into City (id, City) values (27, 'Heyin');
insert into City (id, City) values (28, 'Morón');
insert into City (id, City) values (29, 'Boden');
insert into City (id, City) values (30, 'Qinling Jieban');
insert into City (id, City) values (31, 'Pañgobilian');
insert into City (id, City) values (32, 'Nantes');
insert into City (id, City) values (33, 'McKinley');
insert into City (id, City) values (34, 'Lamas');
insert into City (id, City) values (35, 'Skole');
insert into City (id, City) values (36, 'Amarillo');
insert into City (id, City) values (37, 'Lilla Edet');
insert into City (id, City) values (38, 'Dziadkowice');
insert into City (id, City) values (39, 'Kerek');
insert into City (id, City) values (40, 'Berber');
insert into City (id, City) values (41, 'Douala');
insert into City (id, City) values (42, 'Jejkowice');
insert into City (id, City) values (43, 'Oebatu');
insert into City (id, City) values (44, 'Rego');
insert into City (id, City) values (45, 'Syktyvkar');
insert into City (id, City) values (46, 'Fenghua');
insert into City (id, City) values (47, 'Karangpocok');
insert into City (id, City) values (48, 'Bolinao');
insert into City (id, City) values (49, 'Cinyumput');
insert into City (id, City) values (50, 'Tourcoing');
insert into City (id, City) values (51, 'Huyang');
insert into City (id, City) values (52, 'Muladbucad');
insert into City (id, City) values (53, 'Guangping');
insert into City (id, City) values (54, 'Mazongling');
insert into City (id, City) values (55, 'Bytkiv');
insert into City (id, City) values (56, 'Dangshun');
insert into City (id, City) values (57, 'Williston');
insert into City (id, City) values (58, 'Wakayama-shi');
insert into City (id, City) values (59, 'Pemex');
insert into City (id, City) values (60, 'Vyborg');
insert into City (id, City) values (61, 'Masohi');
insert into City (id, City) values (62, 'Ocoyo');
insert into City (id, City) values (63, 'Ungca');
insert into City (id, City) values (64, 'Zebrzydowice');
insert into City (id, City) values (65, 'Tombatu');
insert into City (id, City) values (66, 'Wichit');
insert into City (id, City) values (67, 'Xinjie');
insert into City (id, City) values (68, 'Mengcheng Chengguanzhen');
insert into City (id, City) values (69, 'Obo');
insert into City (id, City) values (70, 'Nianyushan');
insert into City (id, City) values (71, 'Shanlian');
insert into City (id, City) values (72, 'Yengiawat');
insert into City (id, City) values (73, 'Palmas De Gran Canaria, Las');
insert into City (id, City) values (74, 'Ilo');
insert into City (id, City) values (75, 'Maroúsi');
insert into City (id, City) values (76, 'Qinglong');
insert into City (id, City) values (77, 'Tenjolaya');
insert into City (id, City) values (78, 'San José Poaquil');
insert into City (id, City) values (79, 'Heshang');
insert into City (id, City) values (80, 'Sājir');
insert into City (id, City) values (81, 'Rochefort');
insert into City (id, City) values (82, 'Dujuuma');
insert into City (id, City) values (83, 'Konstantinovskoye');
insert into City (id, City) values (84, 'Cajamarca');
insert into City (id, City) values (85, 'Banjar Asahduren');
insert into City (id, City) values (86, 'Namballe');
insert into City (id, City) values (87, 'Obiaruku Quarters');
insert into City (id, City) values (88, 'Guanyinsi');
insert into City (id, City) values (89, 'Tazemmourt');
insert into City (id, City) values (90, 'Miras');
insert into City (id, City) values (91, 'Tây Đằng');
insert into City (id, City) values (92, 'Laliki');
insert into City (id, City) values (93, 'Dongtundu');
insert into City (id, City) values (94, 'Las Flores');
insert into City (id, City) values (95, 'Omišalj');
insert into City (id, City) values (96, 'Jequitinhonha');
insert into City (id, City) values (97, 'Lenīnskīy');
insert into City (id, City) values (98, 'Tambakan');
insert into City (id, City) values (99, 'Fucheng');
insert into City (id, City) values (100, 'Kadupayung');
insert into City (id, City) values (101, 'Neepawa');
insert into City (id, City) values (102, 'Amadeo');
insert into City (id, City) values (103, 'Pomar');
insert into City (id, City) values (104, 'Pedro Leopoldo');
insert into City (id, City) values (105, 'Lębork');
insert into City (id, City) values (106, 'Melaka');
insert into City (id, City) values (107, 'Wilanagara');
insert into City (id, City) values (108, 'Potrerillos Arriba');
insert into City (id, City) values (109, 'San Juan');
insert into City (id, City) values (110, 'Lomme');
insert into City (id, City) values (111, 'Geneng');
insert into City (id, City) values (112, 'Dvurechensk');
insert into City (id, City) values (113, 'Citeureup');
insert into City (id, City) values (114, 'Igreja');
insert into City (id, City) values (115, 'Tīrān');
insert into City (id, City) values (116, 'Kamenický Šenov');
insert into City (id, City) values (117, 'Severnyy');
insert into City (id, City) values (118, 'Malkā');
insert into City (id, City) values (119, 'Skrunda');
insert into City (id, City) values (120, 'Hukou');
insert into City (id, City) values (121, 'Agoncillo');
insert into City (id, City) values (122, 'Zaragoza');
insert into City (id, City) values (123, 'Jingyao');
insert into City (id, City) values (124, 'Gouménissa');
insert into City (id, City) values (125, 'Mmathubudukwane');
insert into City (id, City) values (126, 'Spiczyn');
insert into City (id, City) values (127, 'Padang');
insert into City (id, City) values (128, 'Ceerigaabo');
insert into City (id, City) values (129, 'Örebro');
insert into City (id, City) values (130, 'Barapas');
insert into City (id, City) values (131, 'Haokou');
insert into City (id, City) values (132, 'Kupavna');
insert into City (id, City) values (133, 'Järna');
insert into City (id, City) values (134, 'Ponong');
insert into City (id, City) values (135, 'Cereté');
insert into City (id, City) values (136, 'Camasca');
insert into City (id, City) values (137, 'Wąpielsk');
insert into City (id, City) values (138, 'Barinitas');
insert into City (id, City) values (139, 'Krajanbaturno');
insert into City (id, City) values (140, 'Lyon');
insert into City (id, City) values (141, 'Tomakivka');
insert into City (id, City) values (142, 'Jiefang');
insert into City (id, City) values (143, 'Évry');
insert into City (id, City) values (144, 'Quzhou');
insert into City (id, City) values (145, 'Oslo');
insert into City (id, City) values (146, 'Sittwe');
insert into City (id, City) values (147, 'Kutno');
insert into City (id, City) values (148, 'Shankill');
insert into City (id, City) values (149, 'Alcáçovas');
insert into City (id, City) values (150, 'Yujin');
insert into City (id, City) values (151, 'Sumbergayam');
insert into City (id, City) values (152, 'Krajan');
insert into City (id, City) values (153, 'Kuštilj');
insert into City (id, City) values (154, 'Delok');
insert into City (id, City) values (155, 'Pinheiros');
insert into City (id, City) values (156, 'Jelisavac');
insert into City (id, City) values (157, 'Xamtay');
insert into City (id, City) values (158, 'Xiashitai');
insert into City (id, City) values (159, 'Embarcación');
insert into City (id, City) values (160, 'Longueuil');
insert into City (id, City) values (161, 'Puerto Plata');
insert into City (id, City) values (162, 'Kuantan');
insert into City (id, City) values (163, 'Aigínio');
insert into City (id, City) values (164, 'Cikalang');
insert into City (id, City) values (165, 'Wonopringgo');
insert into City (id, City) values (166, 'Daba');
insert into City (id, City) values (167, 'Hamar');
insert into City (id, City) values (168, 'Gierałtowice');
insert into City (id, City) values (169, 'Nantes');
insert into City (id, City) values (170, 'Xiaping');
insert into City (id, City) values (171, 'Skövde');
insert into City (id, City) values (172, 'Taiyuan');
insert into City (id, City) values (173, 'Јегуновце');
insert into City (id, City) values (174, 'Mekkaw');
insert into City (id, City) values (175, 'Tân Việt');
insert into City (id, City) values (176, 'Oefatu');
insert into City (id, City) values (177, 'Kovernino');
insert into City (id, City) values (178, 'Cernik');
insert into City (id, City) values (179, 'Valka');
insert into City (id, City) values (180, 'Sanom');
insert into City (id, City) values (181, 'Ankazobe');
insert into City (id, City) values (182, 'Mytishchi');
insert into City (id, City) values (183, 'Czerniewice');
insert into City (id, City) values (184, 'Jingxi');
insert into City (id, City) values (185, 'Verkhnya Syrovatka');
insert into City (id, City) values (186, 'Várzea Grande');
insert into City (id, City) values (187, 'Farshūţ');
insert into City (id, City) values (188, 'Podsineye');
insert into City (id, City) values (189, 'Xiniqi');
insert into City (id, City) values (190, 'España');
insert into City (id, City) values (191, 'Sangar Sarāy');
insert into City (id, City) values (192, 'Datian');
insert into City (id, City) values (193, 'Jiaotang');
insert into City (id, City) values (194, 'Baltimore');
insert into City (id, City) values (195, 'Huanghua');
insert into City (id, City) values (196, 'Mytishchi');
insert into City (id, City) values (197, 'Lanlongkou');
insert into City (id, City) values (198, 'Uritsk');
insert into City (id, City) values (199, 'Santa Maria');
insert into City (id, City) values (200, 'Vishnyeva');
insert into City (id, City) values (201, 'Barajalan');
insert into City (id, City) values (202, 'Pouso Alegre');
insert into City (id, City) values (203, 'Fuwah');
insert into City (id, City) values (204, 'Pengchang');
insert into City (id, City) values (205, 'Fresno');
insert into City (id, City) values (206, 'Mosal’sk');
insert into City (id, City) values (207, 'Tibillo');
insert into City (id, City) values (208, 'Parque Industrial');
insert into City (id, City) values (209, 'Oslo');
insert into City (id, City) values (210, 'Congkar');
insert into City (id, City) values (211, 'Luba');
insert into City (id, City) values (212, 'Dębno');
insert into City (id, City) values (213, 'As Sab‘ Biyār');
insert into City (id, City) values (214, 'Bergen');
insert into City (id, City) values (215, 'Messíni');
insert into City (id, City) values (216, 'Zarumilla');
insert into City (id, City) values (217, 'Qianhong');
insert into City (id, City) values (218, 'Puerto Plata');
insert into City (id, City) values (219, 'Cuilco');
insert into City (id, City) values (220, 'Guanba');
insert into City (id, City) values (221, 'Ādīs Zemen');
insert into City (id, City) values (222, 'Mabini');
insert into City (id, City) values (223, 'Kronoby');
insert into City (id, City) values (224, 'Vacha');
insert into City (id, City) values (225, 'Regueiro');
insert into City (id, City) values (226, 'Putun');
insert into City (id, City) values (227, 'Balaklava');
insert into City (id, City) values (228, 'Beiqi');
insert into City (id, City) values (229, 'Makurazaki');
insert into City (id, City) values (230, 'Kansas City');
insert into City (id, City) values (231, 'Walton');
insert into City (id, City) values (232, 'Vadstena');
insert into City (id, City) values (233, 'Putinci');
insert into City (id, City) values (234, 'Tawaran');
insert into City (id, City) values (235, 'Koshki');
insert into City (id, City) values (236, 'Daye');
insert into City (id, City) values (237, 'Amouguer');
insert into City (id, City) values (238, 'Bria');
insert into City (id, City) values (239, 'Thành Phố Bà Rịa');
insert into City (id, City) values (240, 'Barnaul');
insert into City (id, City) values (241, 'Tha Tako');
insert into City (id, City) values (242, 'Gvozd');
insert into City (id, City) values (243, 'Borås');
insert into City (id, City) values (244, 'Zambrów');
insert into City (id, City) values (245, 'Dengok');
insert into City (id, City) values (246, 'Bells Corners');
insert into City (id, City) values (247, 'Zgornje Bitnje');
insert into City (id, City) values (248, 'Shimen');
insert into City (id, City) values (249, 'Vila Nova de Santo André');
insert into City (id, City) values (250, 'Yekaterinovka');
insert into City (id, City) values (251, 'Kuala Lumpur');
insert into City (id, City) values (252, 'Santa Inês');
insert into City (id, City) values (253, 'San Bautista');
insert into City (id, City) values (254, 'Dongjia');
insert into City (id, City) values (255, 'Shimorskoye');
insert into City (id, City) values (256, 'Fastiv');
insert into City (id, City) values (257, 'Nkove');
insert into City (id, City) values (258, 'Pitogo');
insert into City (id, City) values (259, 'Looc');
insert into City (id, City) values (260, 'Staryy Togul');
insert into City (id, City) values (261, 'Opatów');
insert into City (id, City) values (262, 'Malasiqui');
insert into City (id, City) values (263, 'Yanglinqiao');
insert into City (id, City) values (264, 'Kemlya');
insert into City (id, City) values (265, 'Guadalupe');
insert into City (id, City) values (266, 'Salvador');
insert into City (id, City) values (267, 'Lamego');
insert into City (id, City) values (268, 'Baoshan');
insert into City (id, City) values (269, 'San Juan');
insert into City (id, City) values (270, 'Bagamoyo');
insert into City (id, City) values (271, 'Rucheng Chengguanzhen');
insert into City (id, City) values (272, 'Ciparakan');
insert into City (id, City) values (273, 'Białośliwie');
insert into City (id, City) values (274, 'Lyakhovtsy');
insert into City (id, City) values (275, 'Gwanda');
insert into City (id, City) values (276, 'Wuxing');
insert into City (id, City) values (277, 'Mobile');
insert into City (id, City) values (278, 'Mizur');
insert into City (id, City) values (279, 'Karviná');
insert into City (id, City) values (280, 'Circasia');
insert into City (id, City) values (281, 'Vitória do Mearim');
insert into City (id, City) values (282, 'Stakhanov');
insert into City (id, City) values (283, 'Achadinha');
insert into City (id, City) values (284, 'Vitim');
insert into City (id, City) values (285, 'Bissau');
insert into City (id, City) values (286, 'Laifang');
insert into City (id, City) values (287, 'Zhukovo');
insert into City (id, City) values (288, 'Cabañas');
insert into City (id, City) values (289, 'Kafr Şaqr');
insert into City (id, City) values (290, 'Katrineholm');
insert into City (id, City) values (291, 'Reni');
insert into City (id, City) values (292, 'Bacheng');
insert into City (id, City) values (293, 'Ibotirama');
insert into City (id, City) values (294, 'Oeiras');
insert into City (id, City) values (295, 'Hofors');
insert into City (id, City) values (296, 'Toulon');
insert into City (id, City) values (297, 'Côn Sơn');
insert into City (id, City) values (298, 'Beisijiazi');
insert into City (id, City) values (299, 'Koror Town');
insert into City (id, City) values (300, 'Calumpang');
insert into City (id, City) values (301, 'Musan-ŭp');
insert into City (id, City) values (302, 'Xindong');
insert into City (id, City) values (303, 'Xinmin');
insert into City (id, City) values (304, 'København');
insert into City (id, City) values (305, 'Sredniy');
insert into City (id, City) values (306, 'Alexandria');
insert into City (id, City) values (307, 'Jardim da Serra');
insert into City (id, City) values (308, 'Quintães');
insert into City (id, City) values (309, 'Jinhua');
insert into City (id, City) values (310, 'Karmah an Nuzul');
insert into City (id, City) values (311, 'Iradan');
insert into City (id, City) values (312, 'Mongaguá');
insert into City (id, City) values (313, 'São Martinho de Árvore');
insert into City (id, City) values (314, 'Antonina');
insert into City (id, City) values (315, 'Đông Thành');
insert into City (id, City) values (316, 'Saint-Ouen');
insert into City (id, City) values (317, 'Zamoskvorech’ye');
insert into City (id, City) values (318, 'Sungaipuntik');
insert into City (id, City) values (319, 'Itiruçu');
insert into City (id, City) values (320, 'Vila Nova');
insert into City (id, City) values (321, 'Tegalrejo');
insert into City (id, City) values (322, 'Kubang');
insert into City (id, City) values (323, 'Notodden');
insert into City (id, City) values (324, 'Dongla');
insert into City (id, City) values (325, 'Dulian');
insert into City (id, City) values (326, 'Dolní Bečva');
insert into City (id, City) values (327, 'Dieppe');
insert into City (id, City) values (328, 'Santa Luzia');
insert into City (id, City) values (329, 'Diawara');
insert into City (id, City) values (330, 'Lubień Kujawski');
insert into City (id, City) values (331, 'Amiens');
insert into City (id, City) values (332, 'Langensari');
insert into City (id, City) values (333, 'Jalālpur');
insert into City (id, City) values (334, 'Dumalneg');
insert into City (id, City) values (335, 'Chengmagang');
insert into City (id, City) values (336, 'Jeblog Satu');
insert into City (id, City) values (337, 'Duli');
insert into City (id, City) values (338, 'Ílion');
insert into City (id, City) values (339, 'Carepa');
insert into City (id, City) values (340, 'Bilhorod-Dnistrovs’kyy');
insert into City (id, City) values (341, 'Ipoh');
insert into City (id, City) values (342, 'Bayside');
insert into City (id, City) values (343, 'Albuquerque');
insert into City (id, City) values (344, 'Basing');
insert into City (id, City) values (345, 'San Pedro');
insert into City (id, City) values (346, 'Touying');
insert into City (id, City) values (347, 'Ōdachō-ōda');
insert into City (id, City) values (348, 'Ramana');
insert into City (id, City) values (349, 'Oslo');
insert into City (id, City) values (350, 'Pisões');
insert into City (id, City) values (351, 'Ludbreg');
insert into City (id, City) values (352, 'Alençon');
insert into City (id, City) values (353, 'Itaboraí');
insert into City (id, City) values (354, 'Sucre');
insert into City (id, City) values (355, 'Lerrnanist');
insert into City (id, City) values (356, 'Thị Trấn Ngan Dừa');
insert into City (id, City) values (357, 'Non Suwan');
insert into City (id, City) values (358, 'Panan');
insert into City (id, City) values (359, 'Xia Zanggor');
insert into City (id, City) values (360, 'Bressuire');
insert into City (id, City) values (361, 'Jincheng');
insert into City (id, City) values (362, 'Kipit');
insert into City (id, City) values (363, 'Luzino');
insert into City (id, City) values (364, 'Viga');
insert into City (id, City) values (365, 'Czarna');
insert into City (id, City) values (366, 'Santo Niño');
insert into City (id, City) values (367, 'Huage');
insert into City (id, City) values (368, 'Sucre');
insert into City (id, City) values (369, 'Mtsamdou');
insert into City (id, City) values (370, 'Santo Domingo');
insert into City (id, City) values (371, 'Planaltina');
insert into City (id, City) values (372, 'Henglin');
insert into City (id, City) values (373, 'Kukuna');
insert into City (id, City) values (374, 'Kijini');
insert into City (id, City) values (375, 'Łęki');
insert into City (id, City) values (376, 'Jarash');
insert into City (id, City) values (377, 'Yanjiang');
insert into City (id, City) values (378, 'Kaputian');
insert into City (id, City) values (379, 'Pamotan');
insert into City (id, City) values (380, 'Valuyki');
insert into City (id, City) values (381, 'Na Khu');
insert into City (id, City) values (382, 'Talshand');
insert into City (id, City) values (383, 'Rio do Sul');
insert into City (id, City) values (384, 'Oakland');
insert into City (id, City) values (385, 'Dong’an');
insert into City (id, City) values (386, 'Tungao');
insert into City (id, City) values (387, 'Bārkhān');
insert into City (id, City) values (388, 'Kamenka');
insert into City (id, City) values (389, 'Shkodër');
insert into City (id, City) values (390, 'Svenljunga');
insert into City (id, City) values (391, 'Fuchang');
insert into City (id, City) values (392, 'Krasnogorsk');
insert into City (id, City) values (393, 'Tobias Fornier');
insert into City (id, City) values (394, 'Norrtälje');
insert into City (id, City) values (395, 'Bhamdoun');
insert into City (id, City) values (396, 'Niutian');
insert into City (id, City) values (397, 'Idrinskoye');
insert into City (id, City) values (398, 'Mundão');
insert into City (id, City) values (399, 'Cincinnati');
insert into City (id, City) values (400, 'San Sebastián');
insert into City (id, City) values (401, 'Kokkinóchoma');
insert into City (id, City) values (402, 'Kangshan');
insert into City (id, City) values (403, 'Riachos');
insert into City (id, City) values (404, 'Melíssia');
insert into City (id, City) values (405, 'Novikovo');
insert into City (id, City) values (406, 'Paris 14');
insert into City (id, City) values (407, 'Araçoiaba da Serra');
insert into City (id, City) values (408, 'Huaraz');
insert into City (id, City) values (409, 'Rouen');
insert into City (id, City) values (410, 'Cupira');
insert into City (id, City) values (411, 'Baykit');
insert into City (id, City) values (412, 'Kawerau');
insert into City (id, City) values (413, 'Santiago do Cacém');
insert into City (id, City) values (414, 'Chizhou');
insert into City (id, City) values (415, 'Rodionovo-Nesvetayskaya');
insert into City (id, City) values (416, 'Bachuan');
insert into City (id, City) values (417, 'Jiuzhai');
insert into City (id, City) values (418, 'Majagual');
insert into City (id, City) values (419, 'Jiangcheng');
insert into City (id, City) values (420, 'San José Poaquil');
insert into City (id, City) values (421, 'Nancheng');
insert into City (id, City) values (422, 'Lewodoli');
insert into City (id, City) values (423, 'Saint John’s');
insert into City (id, City) values (424, 'Antequera');
insert into City (id, City) values (425, 'Zubří');
insert into City (id, City) values (426, 'Hekou');
insert into City (id, City) values (427, 'Khawr Maksar');
insert into City (id, City) values (428, 'Bohicon');
insert into City (id, City) values (429, 'Mēga');
insert into City (id, City) values (430, 'Garagoa');
insert into City (id, City) values (431, 'Anao');
insert into City (id, City) values (432, 'Cuauhtemoc');
insert into City (id, City) values (433, 'Mantes-la-Jolie');
insert into City (id, City) values (434, 'Vila Chã');
insert into City (id, City) values (435, 'Morcellemont Saint André');
insert into City (id, City) values (436, 'Wohyń');
insert into City (id, City) values (437, 'Ardee');
insert into City (id, City) values (438, 'Borlänge');
insert into City (id, City) values (439, 'Fanhu');
insert into City (id, City) values (440, 'Petite Anse');
insert into City (id, City) values (441, 'Santong');
insert into City (id, City) values (442, 'Buan');
insert into City (id, City) values (443, 'Police nad Metují');
insert into City (id, City) values (444, 'Paços');
insert into City (id, City) values (445, 'Toukh');
insert into City (id, City) values (446, 'Wongka');
insert into City (id, City) values (447, 'Krajan Craken');
insert into City (id, City) values (448, 'Zvečan');
insert into City (id, City) values (449, 'Shuntian');
insert into City (id, City) values (450, 'Brunflo');
insert into City (id, City) values (451, 'Makamba');
insert into City (id, City) values (452, 'Kyurdarmir');
insert into City (id, City) values (453, 'Ribeira Grande');
insert into City (id, City) values (454, 'Grubišno Polje');
insert into City (id, City) values (455, 'Hushi');
insert into City (id, City) values (456, 'Korosten’');
insert into City (id, City) values (457, 'Balkh');
insert into City (id, City) values (458, 'Almodôvar');
insert into City (id, City) values (459, 'San Carlos');
insert into City (id, City) values (460, 'Jaraguá');
insert into City (id, City) values (461, 'Rada Tilly');
insert into City (id, City) values (462, 'Sangju');
insert into City (id, City) values (463, 'Tralee');
insert into City (id, City) values (464, 'Chaoyang');
insert into City (id, City) values (465, 'Smolec');
insert into City (id, City) values (466, 'Górzno');
insert into City (id, City) values (467, 'Jocotenango');
insert into City (id, City) values (468, 'Tuhe');
insert into City (id, City) values (469, 'Āstārā');
insert into City (id, City) values (470, 'San Rafael');
insert into City (id, City) values (471, 'Zgornje Jezersko');
insert into City (id, City) values (472, 'Kawangkoan');
insert into City (id, City) values (473, 'Kemuning');
insert into City (id, City) values (474, 'Balingasag');
insert into City (id, City) values (475, 'El Zapote');
insert into City (id, City) values (476, 'Anguera');
insert into City (id, City) values (477, 'Gaocang');
insert into City (id, City) values (478, 'Colonia Aurora');
insert into City (id, City) values (479, 'El Bolsón');
insert into City (id, City) values (480, 'Liboran');
insert into City (id, City) values (481, 'Mocajuba');
insert into City (id, City) values (482, 'Kwangyang');
insert into City (id, City) values (483, 'Lidköping');
insert into City (id, City) values (484, 'Ķegums');
insert into City (id, City) values (485, 'Barreira');
insert into City (id, City) values (486, 'Lampang');
insert into City (id, City) values (487, 'Lalībela');
insert into City (id, City) values (488, 'Nianqiao');
insert into City (id, City) values (489, 'Chastyye');
insert into City (id, City) values (490, 'Vallenar');
insert into City (id, City) values (491, 'Zhanaozen');
insert into City (id, City) values (492, 'Bahía Blanca');
insert into City (id, City) values (493, 'Khānpur');
insert into City (id, City) values (494, 'Kaoshan');
insert into City (id, City) values (495, 'Opuzen');
insert into City (id, City) values (496, 'Middleton');
insert into City (id, City) values (497, 'Kertayuga');
insert into City (id, City) values (498, 'Xiaocun');
insert into City (id, City) values (499, 'Mohelno');
insert into City (id, City) values (500, 'Smolino');
insert into City (id, City) values (501, 'Qarshi');
insert into City (id, City) values (502, 'Vänersborg');
insert into City (id, City) values (503, 'Tongzhong');
insert into City (id, City) values (504, 'Niebocko');
insert into City (id, City) values (505, 'Vangaži');
insert into City (id, City) values (506, 'Arcoverde');
insert into City (id, City) values (507, 'Sundbyberg');
insert into City (id, City) values (508, 'Dawan');
insert into City (id, City) values (509, 'Gasan');
insert into City (id, City) values (510, 'Arari');
insert into City (id, City) values (511, 'Bomadi');
insert into City (id, City) values (512, 'Xiaoduchuan');
insert into City (id, City) values (513, 'Macinhata da Seixa');
insert into City (id, City) values (514, 'Hadapu Zhen');
insert into City (id, City) values (515, 'Lordegān');
insert into City (id, City) values (516, 'Sumberarumkrajan');
insert into City (id, City) values (517, 'Khashuri');
insert into City (id, City) values (518, 'Yunlu');
insert into City (id, City) values (519, 'Kamenskiy');
insert into City (id, City) values (520, 'Den Haag');
insert into City (id, City) values (521, 'Baturinggit Kaja');
insert into City (id, City) values (522, 'Moulins');
insert into City (id, City) values (523, 'Mirandela');
insert into City (id, City) values (524, 'Ţayyibat al Imām');
insert into City (id, City) values (525, 'Kadusirung Hilir');
insert into City (id, City) values (526, 'Corral de Bustos');
insert into City (id, City) values (527, 'Tabant');
insert into City (id, City) values (528, 'Kirtipur');
insert into City (id, City) values (529, 'Mlowo');
insert into City (id, City) values (530, 'Périgueux');
insert into City (id, City) values (531, 'Volokolamsk');
insert into City (id, City) values (532, 'Lue Amnat');
insert into City (id, City) values (533, 'Hövsan');
insert into City (id, City) values (534, 'Odeleite');
insert into City (id, City) values (535, 'Kuala Lumpur');
insert into City (id, City) values (536, 'Kristianstad');
insert into City (id, City) values (537, 'Umingan');
insert into City (id, City) values (538, 'Vynohradiv');
insert into City (id, City) values (539, 'Nanhe');
insert into City (id, City) values (540, 'Ormož');
insert into City (id, City) values (541, 'Kuching');
insert into City (id, City) values (542, 'Tiguion');
insert into City (id, City) values (543, 'Bonnyville');
insert into City (id, City) values (544, 'Główczyce');
insert into City (id, City) values (545, 'Boromlya');
insert into City (id, City) values (546, 'Sigeng');
insert into City (id, City) values (547, 'Novoselitsa');
insert into City (id, City) values (548, 'Gunungbatu');
insert into City (id, City) values (549, 'Praia da Tocha');
insert into City (id, City) values (550, 'Yinyang');
insert into City (id, City) values (551, 'Pilar');
insert into City (id, City) values (552, 'Penang');
insert into City (id, City) values (553, 'Daqian');
insert into City (id, City) values (554, 'Rosmaninhal');
insert into City (id, City) values (555, 'Teresópolis');
insert into City (id, City) values (556, 'Xiangyanglu');
insert into City (id, City) values (557, 'Qionghu');
insert into City (id, City) values (558, 'Xincheng');
insert into City (id, City) values (559, 'Bobon');
insert into City (id, City) values (560, 'Namwala');
insert into City (id, City) values (561, 'Ijebu-Ife');
insert into City (id, City) values (562, 'Killumney');
insert into City (id, City) values (563, 'Krajan');
insert into City (id, City) values (564, 'Ruukki');
insert into City (id, City) values (565, 'Chatan');
insert into City (id, City) values (566, 'Trelleborg');
insert into City (id, City) values (567, 'Tögrög');
insert into City (id, City) values (568, 'Dukuh');
insert into City (id, City) values (569, 'Myitkyina');
insert into City (id, City) values (570, 'Paitan');
insert into City (id, City) values (571, 'Ambarakaraka');
insert into City (id, City) values (572, 'Graksop');
insert into City (id, City) values (573, 'San Ignacio de Tupile');
insert into City (id, City) values (574, 'Mahuta');
insert into City (id, City) values (575, 'Digkilaan');
insert into City (id, City) values (576, 'Parigi');
insert into City (id, City) values (577, 'Zubin Potok');
insert into City (id, City) values (578, 'Caramay');
insert into City (id, City) values (579, 'Tairan Camp');
insert into City (id, City) values (580, 'Örnsköldsvik');
insert into City (id, City) values (581, 'Hrušovany u Brna');
insert into City (id, City) values (582, 'Yafran');
insert into City (id, City) values (583, 'Seattle');
insert into City (id, City) values (584, 'Warugunung');
insert into City (id, City) values (585, 'Talanga');
insert into City (id, City) values (586, 'Quince Mil');
insert into City (id, City) values (587, 'Claveria');
insert into City (id, City) values (588, 'Gorno-Altaysk');
insert into City (id, City) values (589, 'Smålandsstenar');
insert into City (id, City) values (590, 'Colesberg');
insert into City (id, City) values (591, 'Butiama');
insert into City (id, City) values (592, 'Omaha');
insert into City (id, City) values (593, 'Quezon');
insert into City (id, City) values (594, 'Lengor');
insert into City (id, City) values (595, 'Comal');
insert into City (id, City) values (596, 'Estância');
insert into City (id, City) values (597, 'Miastków Kościelny');
insert into City (id, City) values (598, 'Port-Cartier');
insert into City (id, City) values (599, 'San Remigio');
insert into City (id, City) values (600, 'Vicente Guerrero');
insert into City (id, City) values (601, 'Zuru');
insert into City (id, City) values (602, 'Juàzeirinho');
insert into City (id, City) values (603, 'Chengnan');
insert into City (id, City) values (604, 'Guayatá');
insert into City (id, City) values (605, 'Hangji');
insert into City (id, City) values (606, 'Maguilling');
insert into City (id, City) values (607, 'Neiguan');
insert into City (id, City) values (608, 'Bërxull');
insert into City (id, City) values (609, 'Pulong Gubat');
insert into City (id, City) values (610, 'Palestina');
insert into City (id, City) values (611, 'Thika');
insert into City (id, City) values (612, 'New Pandanon');
insert into City (id, City) values (613, 'Matungao');
insert into City (id, City) values (614, 'Sadang Kulon');
insert into City (id, City) values (615, 'Ranambeling');
insert into City (id, City) values (616, 'Huanfeng');
insert into City (id, City) values (617, 'Opol');
insert into City (id, City) values (618, 'Port-Cartier');
insert into City (id, City) values (619, 'Sanxi');
insert into City (id, City) values (620, 'Bistrinci');
insert into City (id, City) values (621, 'Stockholm');
insert into City (id, City) values (622, 'Segong');
insert into City (id, City) values (623, 'Beausejour');
insert into City (id, City) values (624, 'Lipov');
insert into City (id, City) values (625, 'General Martín Miguel de Güemes');
insert into City (id, City) values (626, 'Svislach');
insert into City (id, City) values (627, 'Vagos');
insert into City (id, City) values (628, 'Daba');
insert into City (id, City) values (629, 'Nguru');
insert into City (id, City) values (630, 'Neglasari');
insert into City (id, City) values (631, 'Nanxing');
insert into City (id, City) values (632, 'Murzuq');
insert into City (id, City) values (633, 'Biecz');
insert into City (id, City) values (634, 'Lakkha Nëvre');
insert into City (id, City) values (635, 'Calauag');
insert into City (id, City) values (636, 'Uspenka');
insert into City (id, City) values (637, 'Tokoname');
insert into City (id, City) values (638, 'Chancay');
insert into City (id, City) values (639, 'Pochinki');
insert into City (id, City) values (640, 'Massy');
insert into City (id, City) values (641, 'Oepuah');
insert into City (id, City) values (642, 'Tailing');
insert into City (id, City) values (643, 'Colonia Elisa');
insert into City (id, City) values (644, 'Kota Bharu');
insert into City (id, City) values (645, 'Kuaro');
insert into City (id, City) values (646, 'Muskegon');
insert into City (id, City) values (647, 'Huangjin');
insert into City (id, City) values (648, 'Changling');
insert into City (id, City) values (649, 'Knin');
insert into City (id, City) values (650, 'Sidenreng');
insert into City (id, City) values (651, 'Rāvar');
insert into City (id, City) values (652, 'Calle Blancos');
insert into City (id, City) values (653, 'Nidek');
insert into City (id, City) values (654, 'Huangmao');
insert into City (id, City) values (655, 'Cingambul');
insert into City (id, City) values (656, 'Yongfeng');
insert into City (id, City) values (657, 'El Cantón de San Pablo');
insert into City (id, City) values (658, 'Medang');
insert into City (id, City) values (659, 'Bilajari');
insert into City (id, City) values (660, 'Russkiy');
insert into City (id, City) values (661, 'Libušín');
insert into City (id, City) values (662, 'Jingmao');
insert into City (id, City) values (663, 'Andrushivka');
insert into City (id, City) values (664, 'Waoundé');
insert into City (id, City) values (665, 'Yanshou');
insert into City (id, City) values (666, 'Sala');
insert into City (id, City) values (667, 'Vale de Mendiz');
insert into City (id, City) values (668, 'General Enrique Mosconi');
insert into City (id, City) values (669, 'Pulau Pinang');
insert into City (id, City) values (670, 'Öldziyt');
insert into City (id, City) values (671, 'Pillpinto');
insert into City (id, City) values (672, 'Pergan');
insert into City (id, City) values (673, 'Czarnowąsy');
insert into City (id, City) values (674, 'Jinnan');
insert into City (id, City) values (675, 'Hägersten');
insert into City (id, City) values (676, 'Corzuela');
insert into City (id, City) values (677, 'Bella Vista');
insert into City (id, City) values (678, 'Watuweri');
insert into City (id, City) values (679, 'Usogorsk');
insert into City (id, City) values (680, 'San Francisco');
insert into City (id, City) values (681, 'Al Maşdūr');
insert into City (id, City) values (682, 'Gorna Oryakhovitsa');
insert into City (id, City) values (683, 'Banjar Jagasatru');
insert into City (id, City) values (684, 'Swedru');
insert into City (id, City) values (685, 'Vila Maior');
insert into City (id, City) values (686, 'Siaya');
insert into City (id, City) values (687, 'Kansas City');
insert into City (id, City) values (688, 'Kebonan');
insert into City (id, City) values (689, 'Yumaguzino');
insert into City (id, City) values (690, 'G‘azalkent');
insert into City (id, City) values (691, 'Jinhua');
insert into City (id, City) values (692, 'Huanghai');
insert into City (id, City) values (693, 'Hehu');
insert into City (id, City) values (694, 'Tlogotunggal');
insert into City (id, City) values (695, 'San Marcelino');
insert into City (id, City) values (696, 'Biljača');
insert into City (id, City) values (697, 'Yotala');
insert into City (id, City) values (698, 'Ondores');
insert into City (id, City) values (699, 'Ijebu-Ife');
insert into City (id, City) values (700, 'Itiruçu');
insert into City (id, City) values (701, 'Londiani');
insert into City (id, City) values (702, 'Drawno');
insert into City (id, City) values (703, 'Myanaung');
insert into City (id, City) values (704, 'Sidaharja');
insert into City (id, City) values (705, 'Huangjindong');
insert into City (id, City) values (706, 'Sikasso');
insert into City (id, City) values (707, 'Pekijing');
insert into City (id, City) values (708, 'Mosopa');
insert into City (id, City) values (709, 'Amga');
insert into City (id, City) values (710, 'Lyuban’');
insert into City (id, City) values (711, 'Volokolamsk');
insert into City (id, City) values (712, 'Marietta');
insert into City (id, City) values (713, 'Benešov nad Ploučnicí');
insert into City (id, City) values (714, 'Aguilares');
insert into City (id, City) values (715, 'Yanmenguan');
insert into City (id, City) values (716, 'Qiancheng');
insert into City (id, City) values (717, 'Neietsu');
insert into City (id, City) values (718, 'Saint Louis');
insert into City (id, City) values (719, 'Banjar Tengah');
insert into City (id, City) values (720, 'Bianxiong');
insert into City (id, City) values (721, 'Tambo');
insert into City (id, City) values (722, 'Dushang');
insert into City (id, City) values (723, 'Mariental');
insert into City (id, City) values (724, 'Rzeszów');
insert into City (id, City) values (725, 'Luotaping');
insert into City (id, City) values (726, 'Pule');
insert into City (id, City) values (727, 'München');
insert into City (id, City) values (728, 'Mizhhir’ya');
insert into City (id, City) values (729, 'Cibeureum');
insert into City (id, City) values (730, 'Adolfo Lopez Mateos');
insert into City (id, City) values (731, 'Wasquehal');
insert into City (id, City) values (732, 'Gaxung');
insert into City (id, City) values (733, 'Zlaté Hory');
insert into City (id, City) values (734, 'Şabyā');
insert into City (id, City) values (735, 'Kangshan');
insert into City (id, City) values (736, 'Cangkeuteuk Sabrang');
insert into City (id, City) values (737, 'Tha Bo');
insert into City (id, City) values (738, 'Esplanada');
insert into City (id, City) values (739, 'Santiago de María');
insert into City (id, City) values (740, 'Sopo');
insert into City (id, City) values (741, 'Coja');
insert into City (id, City) values (742, 'Taxisco');
insert into City (id, City) values (743, 'Santa Nino');
insert into City (id, City) values (744, 'Ambato');
insert into City (id, City) values (745, 'Palhais');
insert into City (id, City) values (746, 'Berlin');
insert into City (id, City) values (747, 'Kórnik');
insert into City (id, City) values (748, 'Nynäshamn');
insert into City (id, City) values (749, 'Bandhagen');
insert into City (id, City) values (750, 'Makoko');
insert into City (id, City) values (751, 'Langensari');
insert into City (id, City) values (752, 'Ytterby');
insert into City (id, City) values (753, 'Cibeureum');
insert into City (id, City) values (754, 'Villa María');
insert into City (id, City) values (755, 'Bajiao');
insert into City (id, City) values (756, 'Bobigny');
insert into City (id, City) values (757, 'Campo Largo');
insert into City (id, City) values (758, 'Gawanan');
insert into City (id, City) values (759, 'Klenje');
insert into City (id, City) values (760, 'Dijon');
insert into City (id, City) values (761, 'Bojongsari');
insert into City (id, City) values (762, 'Geumpang');
insert into City (id, City) values (763, 'Kuncen');
insert into City (id, City) values (764, 'Naḩḩālīn');
insert into City (id, City) values (765, 'Guanzhou');
insert into City (id, City) values (766, 'Hongshanyao');
insert into City (id, City) values (767, 'Dazhou');
insert into City (id, City) values (768, 'Oula Xiuma');
insert into City (id, City) values (769, 'Bogojevo');
insert into City (id, City) values (770, 'Limoeiro');
insert into City (id, City) values (771, 'Houmt Souk');
insert into City (id, City) values (772, 'Sarmanovo');
insert into City (id, City) values (773, 'Marcara');
insert into City (id, City) values (774, 'Petersfield');
insert into City (id, City) values (775, 'Kojagete');
insert into City (id, City) values (776, 'Kunsan');
insert into City (id, City) values (777, 'Chanuman');
insert into City (id, City) values (778, 'Sabanalarga');
insert into City (id, City) values (779, 'Tintafor');
insert into City (id, City) values (780, 'Rzyki');
insert into City (id, City) values (781, 'Fuxing');
insert into City (id, City) values (782, 'Penha');
insert into City (id, City) values (783, 'Lipljan');
insert into City (id, City) values (784, 'Leninogorsk');
insert into City (id, City) values (785, 'Yilan');
insert into City (id, City) values (786, 'Tonosí');
insert into City (id, City) values (787, 'Lukunor');
insert into City (id, City) values (788, 'Phnom Penh');
insert into City (id, City) values (789, 'Shishan');
insert into City (id, City) values (790, 'Stockholm');
insert into City (id, City) values (791, 'Tongzilin');
insert into City (id, City) values (792, 'Jilib');
insert into City (id, City) values (793, 'Kokembang');
insert into City (id, City) values (794, 'Kawaliwu');
insert into City (id, City) values (795, 'Tetyushi');
insert into City (id, City) values (796, 'Salinas');
insert into City (id, City) values (797, 'Kabala');
insert into City (id, City) values (798, 'Nan');
insert into City (id, City) values (799, 'Pamotan');
insert into City (id, City) values (800, 'Minneapolis');
insert into City (id, City) values (801, 'San Pedro Carchá');
insert into City (id, City) values (802, 'Ombul Barat');
insert into City (id, City) values (803, 'Maracás');
insert into City (id, City) values (804, 'Ostrzeszów');
insert into City (id, City) values (805, 'Taouima');
insert into City (id, City) values (806, 'San Silvestre');
insert into City (id, City) values (807, 'Lons-le-Saunier');
insert into City (id, City) values (808, 'Santa Rita Aplaya');
insert into City (id, City) values (809, 'Jinshi');
insert into City (id, City) values (810, 'Pokój');
insert into City (id, City) values (811, 'Oke Iho');
insert into City (id, City) values (812, 'Rionegro');
insert into City (id, City) values (813, 'Moutsamoudou');
insert into City (id, City) values (814, 'Debelets');
insert into City (id, City) values (815, 'Ribafria');
insert into City (id, City) values (816, 'Titiakar');
insert into City (id, City) values (817, 'Brusy');
insert into City (id, City) values (818, 'Ystad');
insert into City (id, City) values (819, 'Daogao');
insert into City (id, City) values (820, 'Leloboko');
insert into City (id, City) values (821, 'Göteborg');
insert into City (id, City) values (822, 'Dayr al Ghuşūn');
insert into City (id, City) values (823, 'Kista');
insert into City (id, City) values (824, 'Loučná nad Desnou');
insert into City (id, City) values (825, 'Al Judayrah');
insert into City (id, City) values (826, 'Nangan');
insert into City (id, City) values (827, 'Umuquena');
insert into City (id, City) values (828, 'Muramatsu');
insert into City (id, City) values (829, 'Lima Pampa');
insert into City (id, City) values (830, 'Nanaimo');
insert into City (id, City) values (831, 'Retorta');
insert into City (id, City) values (832, 'Jasionów');
insert into City (id, City) values (833, 'Bangan-Oda');
insert into City (id, City) values (834, 'Fayzabad');
insert into City (id, City) values (835, 'Umbulan');
insert into City (id, City) values (836, 'Karata');
insert into City (id, City) values (837, 'Gabi');
insert into City (id, City) values (838, 'Chugay');
insert into City (id, City) values (839, 'Baoshan');
insert into City (id, City) values (840, 'Colonia Aurora');
insert into City (id, City) values (841, 'Ishikawa');
insert into City (id, City) values (842, 'Virginia Beach');
insert into City (id, City) values (843, 'Youzha');
insert into City (id, City) values (844, 'Āshtīān');
insert into City (id, City) values (845, 'Boucinha');
insert into City (id, City) values (846, 'Shihua');
insert into City (id, City) values (847, 'Arles');
insert into City (id, City) values (848, 'Diriamba');
insert into City (id, City) values (849, 'Mollās̄ānī');
insert into City (id, City) values (850, 'Jirjā');
insert into City (id, City) values (851, 'Hongmei');
insert into City (id, City) values (852, 'Suchen');
insert into City (id, City) values (853, 'Padova');
insert into City (id, City) values (854, 'Duobagou');
insert into City (id, City) values (855, 'Tommot');
insert into City (id, City) values (856, 'Kubangeceng');
insert into City (id, City) values (857, 'Vendas de Galizes');
insert into City (id, City) values (858, 'Dopang');
insert into City (id, City) values (859, 'Langtang');
insert into City (id, City) values (860, 'Kożuchów');
insert into City (id, City) values (861, 'Melchor de Mencos');
insert into City (id, City) values (862, 'Manadhoo');
insert into City (id, City) values (863, 'Curridabat');
insert into City (id, City) values (864, 'Beiwa');
insert into City (id, City) values (865, 'Tonghu');
insert into City (id, City) values (866, 'Az Zawr');
insert into City (id, City) values (867, 'Žeravice');
insert into City (id, City) values (868, 'Tayabo');
insert into City (id, City) values (869, 'Rodniki');
insert into City (id, City) values (870, 'Årjäng');
insert into City (id, City) values (871, 'Realeza');
insert into City (id, City) values (872, 'Aghavnadzor');
insert into City (id, City) values (873, 'Káto Dhiminió');
insert into City (id, City) values (874, 'Siguinon');
insert into City (id, City) values (875, 'Cabricán');
insert into City (id, City) values (876, 'Girón');
insert into City (id, City) values (877, 'Uthai Thani');
insert into City (id, City) values (878, 'Baiquesi');
insert into City (id, City) values (879, 'Goundam');
insert into City (id, City) values (880, 'Humaitá');
insert into City (id, City) values (881, 'Mao');
insert into City (id, City) values (882, 'Magallanes');
insert into City (id, City) values (883, 'Gostyń');
insert into City (id, City) values (884, 'Battung');
insert into City (id, City) values (885, 'Goujie');
insert into City (id, City) values (886, 'Kahrīz');
insert into City (id, City) values (887, 'Fūman');
insert into City (id, City) values (888, 'Avellaneda');
insert into City (id, City) values (889, 'Pengshi');
insert into City (id, City) values (890, 'Río Colorado');
insert into City (id, City) values (891, 'Knin');
insert into City (id, City) values (892, 'Megalochórion');
insert into City (id, City) values (893, 'Gwanda');
insert into City (id, City) values (894, 'Saray');
insert into City (id, City) values (895, 'Neklyudovo');
insert into City (id, City) values (896, 'Campo Largo');
insert into City (id, City) values (897, 'Zhaoyuan');
insert into City (id, City) values (898, 'Västerås');
insert into City (id, City) values (899, 'Lawepakam');
insert into City (id, City) values (900, 'Antipino');
insert into City (id, City) values (901, 'Pridraga');
insert into City (id, City) values (902, 'Amagarapati');
insert into City (id, City) values (903, 'Luleå');
insert into City (id, City) values (904, 'Santa Teresa');
insert into City (id, City) values (905, 'Shīrvān');
insert into City (id, City) values (906, 'Futang');
insert into City (id, City) values (907, 'Gradac');
insert into City (id, City) values (908, 'San José de las Lajas');
insert into City (id, City) values (909, 'Xiongzhou');
insert into City (id, City) values (910, 'Esmeralda');
insert into City (id, City) values (911, 'Jand');
insert into City (id, City) values (912, 'Casma');
insert into City (id, City) values (913, 'Thị Trấn Nho Quan');
insert into City (id, City) values (914, 'Dijon');
insert into City (id, City) values (915, 'El Águila');
insert into City (id, City) values (916, 'Montijo');
insert into City (id, City) values (917, 'Fengshan');
insert into City (id, City) values (918, 'Plaza Huincul');
insert into City (id, City) values (919, 'Coutada');
insert into City (id, City) values (920, 'Staropyshminsk');
insert into City (id, City) values (921, 'Oslo');
insert into City (id, City) values (922, 'Lima');
insert into City (id, City) values (923, 'Gaocang');
insert into City (id, City) values (924, 'Zhoutie');
insert into City (id, City) values (925, 'Tayu');
insert into City (id, City) values (926, 'Xunjian');
insert into City (id, City) values (927, 'Yangiobod');
insert into City (id, City) values (928, 'Estrada');
insert into City (id, City) values (929, 'Luar');
insert into City (id, City) values (930, 'København');
insert into City (id, City) values (931, 'Santo Rosario');
insert into City (id, City) values (932, 'New Orleans');
insert into City (id, City) values (933, 'Caen');
insert into City (id, City) values (934, 'Bandar-e Lengeh');
insert into City (id, City) values (935, 'Amaigbo');
insert into City (id, City) values (936, 'Anjie');
insert into City (id, City) values (937, 'Umunede');
insert into City (id, City) values (938, 'Utrecht (stad)');
insert into City (id, City) values (939, 'Tilang');
insert into City (id, City) values (940, 'Jiaokou');
insert into City (id, City) values (941, 'Čair');
insert into City (id, City) values (942, 'Zabrat');
insert into City (id, City) values (943, 'Gaobeijie');
insert into City (id, City) values (944, 'Cigenca');
insert into City (id, City) values (945, 'Panadtaban');
insert into City (id, City) values (946, 'Amiens');
insert into City (id, City) values (947, 'Neuss');
insert into City (id, City) values (948, 'Barranca');
insert into City (id, City) values (949, 'Zargarān');
insert into City (id, City) values (950, 'Gupakan');
insert into City (id, City) values (951, 'Rožmitál pod Třemšínem');
insert into City (id, City) values (952, 'Āshkhāneh');
insert into City (id, City) values (953, 'Uthal');
insert into City (id, City) values (954, 'Sveg');
insert into City (id, City) values (955, 'Churubamba');
insert into City (id, City) values (956, 'Valerik');
insert into City (id, City) values (957, 'Banyumas');
insert into City (id, City) values (958, 'Masalovka');
insert into City (id, City) values (959, 'Manaus');
insert into City (id, City) values (960, 'Andilamena');
insert into City (id, City) values (961, 'Zhuangtou');
insert into City (id, City) values (962, '‘Abs');
insert into City (id, City) values (963, 'Sitajara');
insert into City (id, City) values (964, 'Fort Lauderdale');
insert into City (id, City) values (965, 'Boa Vista');
insert into City (id, City) values (966, 'Kamyshin');
insert into City (id, City) values (967, 'Pahing Jalatrang');
insert into City (id, City) values (968, 'At-Bashi');
insert into City (id, City) values (969, 'Quivilla');
insert into City (id, City) values (970, 'Tombatu');
insert into City (id, City) values (971, 'Retkovci');
insert into City (id, City) values (972, 'Xinxu');
insert into City (id, City) values (973, 'Arrufó');
insert into City (id, City) values (974, 'Bierawa');
insert into City (id, City) values (975, 'Xinning');
insert into City (id, City) values (976, 'Gongqiao');
insert into City (id, City) values (977, 'Kolirerek');
insert into City (id, City) values (978, 'Trail');
insert into City (id, City) values (979, 'Uralets');
insert into City (id, City) values (980, 'Brnaze');
insert into City (id, City) values (981, 'Linköping');
insert into City (id, City) values (982, 'Lindavista');
insert into City (id, City) values (983, 'Bandaran');
insert into City (id, City) values (984, 'Portland');
insert into City (id, City) values (985, 'Jinjiahe');
insert into City (id, City) values (986, 'Storuman');
insert into City (id, City) values (987, 'Bajos de Haina');
insert into City (id, City) values (988, 'Thaba Nchu');
insert into City (id, City) values (989, 'Jokkmokk');
insert into City (id, City) values (990, 'Bous');
insert into City (id, City) values (991, 'Suwaru');
insert into City (id, City) values (992, 'Henglin');
insert into City (id, City) values (993, 'Toulouse');
insert into City (id, City) values (994, 'Guadalupe');
insert into City (id, City) values (995, 'Nawá');
insert into City (id, City) values (996, 'Shouchang');
insert into City (id, City) values (997, 'Jisegumen');
insert into City (id, City) values (998, 'Selnica');
insert into City (id, City) values (999, 'Gandra');
insert into City (id, City) values (1000, 'Kozmice');
